"""Unique SEO copy for geo pages — Serper-informed, non-duplicated across cities."""

from __future__ import annotations

CITY_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "safety-harbor": {
        "hero_lead": 'Handyman repairs in Safety Harbor — registered, insured Safety Harbor crew serving downtown.',
        "meta_description": 'Safety Harbor handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Knight Group Handyman Services LLC dispatches from 1225 7th St S in Safety Harbor. Safety Harbor is on those routes — you reach the local crew, not a franchise call center. Same-day routing is easiest here, and Vince Knight knows the mix of older downtown stock and newer infill along McMullen-Booth.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Safety Harbor jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": 'Explore our {county_link}, browse the Safety Harbor job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.',
        "faq_price": ('How much does a typical handyman visit cost in Safety Harbor?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Safety Harbor scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Safety Harbor?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Safety Harbor; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Safety Harbor?', 'Most Safety Harbor requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "clearwater": {
        "hero_lead": 'Clearwater handyman from Safety Harbor — $150 first hour, $75 after, no two-hour minimum. Island Estates, Countryside, Coachman, and inland homes.',
        "meta_description": 'Clearwater handyman for drywall, fixtures, doors, and punch lists. $150 first hour, $75 after. No 2-hour minimum. Free written estimate. Call (813) 649-3341.',
        "opening": 'Knight Group is the Safety Harbor handyman already showing up for Clearwater searches — $150 the first hour, $75 after, and no two-hour minimum. We quote in writing before tools come out, then batch Island Estates, Countryside, Coachman, and inland ranch stops on the same Pinellas loop. Beach condos and owner-occupied homes get the same crew: fixture plumbing, drywall, doors, screens, fans, and punch lists — not a franchise call center.',
        "scheduling": "Clearwater is on our regular Pinellas route from Safety Harbor. Most requests schedule within one to two business days. Share the address and photos so we lock an arrival window — call (813) 649-3341 for active water.",
        "scope_note": 'We hang ceiling fans, swap light fixtures, and replace switches and like-for-like outlets on existing circuits. Faucets, toilets, sinks, and fixture plumbing on existing connections are standard Clearwater calls. New circuits, panel work, rewires, repipes, and sewer mains are referred.',
        "closing": 'See <a href="/pricing">pricing</a>, <a href="/pinellas-handyman">Pinellas coverage</a>, and real job photos in the <a href="/galleries">gallery</a>. Focused pages: <a href="/clearwater-sink-repair">Clearwater sink repair</a> and <a href="/clearwater-drywall-repair">Clearwater drywall</a>. Active water — phone first.',
        "faq_price": ('How much does a typical handyman visit cost in Clearwater?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Clearwater scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Clearwater?', 'We hang ceiling fans, swap light fixtures, and replace switches and like-for-like outlets on existing circuits. Faucets, toilets, and fixture plumbing on existing connections are standard Clearwater work. We are not a licensed electrician or plumber. New circuits, panel work, rewires, and sewer mains are referred.'),
        "faq_schedule": ('How soon can you reach Clearwater?', 'Most Clearwater requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "dunedin": {
        "hero_lead": 'Handyman repairs in Dunedin — registered, insured Safety Harbor crew serving downtown Dunedin.',
        "meta_description": 'Dunedin handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": "Looking for reliable handyman help in Dunedin? Vince Knight's team handles drywall, doors, paint-ready finishing, and punch-list repairs without a two-hour minimum. Dunedin’s walkable downtown and tight lot lines mean access and parking matter. We plan material carries and protect historic trim profiles when patching — important for homeowners who value the town’s craftsman character.",
        "scheduling": 'Dunedin scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Dunedin visit. Knight Group documents what we can legally perform and refers licensed trades when DBPR or a permit requires it.',
        "closing": 'Look at local proof on our gallery page. Knight Group publishes real Pinellas County project photos, not stock interiors.',
        "faq_price": ('How much does a typical handyman visit cost in Dunedin?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Dunedin scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Dunedin?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Dunedin; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Dunedin?', 'Most Dunedin requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "palm-harbor": {
        "hero_lead": 'Handyman repairs in Palm Harbor — registered, insured Safety Harbor crew serving East Lake.',
        "meta_description": 'Palm Harbor handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Palm Harbor properties need a contractor who understands local housing stock — not a statewide template page. Knight Group focuses on everyday punch-list work across Pinellas County. East Lake and Highland Lakes homeowners often call for one bathroom issue and discover a short punch list while we are on site. We document each item and quote before expanding scope — common in larger Palm Harbor homes with multiple wet walls.',
        "scheduling": 'Estimates for Palm Harbor work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state contractor license. Palm Harbor homeowners get a clear line between repairs we handle and trades we coordinate.',
        "closing": 'Ready for a Palm Harbor quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does a typical handyman visit cost in Palm Harbor?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Palm Harbor scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Palm Harbor?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Palm Harbor; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Palm Harbor?', 'Most Palm Harbor requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "largo": {
        "hero_lead": 'Handyman repairs in Largo — registered, insured Safety Harbor crew serving Bardmoor.',
        "meta_description": 'Largo handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'From Bardmoor, Knight Group schedules Largo visits with written estimates and an insured crew crossing Pinellas County on planned routes. Largo’s central Pinellas location makes it a natural mid-route stop between Safety Harbor and the beaches. We schedule Bardmoor and Ridgecrest blocks together to keep drive time low and arrival windows tight.',
        "scheduling": 'Planning a Largo repair? Knight Group confirms Pinellas County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: tasks we accept are quoted in writing; anything that needs a licensed trade is flagged before you approve labor.',
        "closing": 'See related service pages, then schedule a Largo visit. Active leaks should be called in so we can triage licensed-trade needs.',
        "faq_price": ('How much does a typical handyman visit cost in Largo?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Largo scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Largo?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Largo; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Largo?', 'Most Largo requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "oldsmar": {
        "hero_lead": 'Handyman repairs in Oldsmar — registered, insured Safety Harbor crew serving East Lake Woodlands edge.',
        "meta_description": 'Oldsmar handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'When storm season stresses doors, screens, and drywall, Oldsmar owners call Knight Group for practical repairs that stay inside current Florida handyman limits. Oldsmar sits on our daily route between Hillsborough jobs and central Pinellas. Homeowners here benefit from a team that already crosses the bay — not a contractor who treats Oldsmar as out of territory.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Oldsmar jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": 'Explore our {county_link}, browse the Oldsmar job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.',
        "faq_price": ('How much does a typical handyman visit cost in Oldsmar?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Oldsmar scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Oldsmar?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Oldsmar; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Oldsmar?', 'Most Oldsmar requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "tarpon-springs": {
        "hero_lead": 'Handyman repairs in Tarpon Springs — registered, insured Safety Harbor crew serving historic district.',
        "meta_description": 'Tarpon Springs handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Knight Group answers Tarpon Springs requests with photos-first estimates, flat-rate quotes on defined scopes, and hourly pricing only when punch lists are open-ended. Tarpon Springs’ older housing stock rewards technicians who understand tight wet walls and fragile tile. Vince Knight’s plumbing background helps diagnose whether a leak stays handyman scope or needs a licensed repipe referral.',
        "scheduling": "We batch Pinellas County routes from our Safety Harbor shop. Share address details for Tarpon Springs when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Tarpon Springs job needs a licensed plumber, electrician, roofer, or permitted contractor, we say so before demolition. Honesty keeps the visit from turning into a change order.',
        "closing": 'Next steps: open the Pinellas County coverage hub, review handyman services and pricing, or book with photos. Active water — phone first.',
        "faq_price": ('How much does a typical handyman visit cost in Tarpon Springs?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Tarpon Springs scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Tarpon Springs?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Tarpon Springs; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Tarpon Springs?', 'Most Tarpon Springs requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "seminole": {
        "hero_lead": 'Handyman repairs in Seminole — registered, insured Safety Harbor crew serving Park Boulevard corridor.',
        "meta_description": 'Seminole handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Seminole homeowners tired of national lead-gen sites choose Knight Group — one Safety Harbor business, one accountable crew. Seminole homeowners along Park Boulevard often need paint-ready drywall repair after humidity stains — we sequence primer, texture, and topcoat so patches do not flash under afternoon sun.',
        "scheduling": 'Seminole scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Seminole visit. Knight Group documents what we can legally perform and refers licensed trades when DBPR or a permit requires it.',
        "closing": 'Look at local proof on our gallery page. Knight Group publishes real Pinellas County project photos, not stock interiors.',
        "faq_price": ('How much does a typical handyman visit cost in Seminole?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Seminole scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Seminole?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Seminole; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Seminole?', 'Most Seminole requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "st-petersburg": {
        "hero_lead": 'Handyman repairs in St. Petersburg — registered, insured Safety Harbor crew serving Kenwood.',
        "meta_description": 'St. Petersburg handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Need a visit in St. Petersburg? Knight Group schedules around existing Pinellas County routes so arrival windows stay realistic and drive time does not inflate your quote. St. Pete’s neighborhood variety means we confirm access, parking, and scope before dispatch — a Kenwood bungalow repair differs from a Tyrone condo turnover. Photos through our booking form speed that conversation.',
        "scheduling": 'Estimates for St. Petersburg work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state contractor license. St. Petersburg homeowners get a clear line between repairs we handle and trades we coordinate.',
        "closing": 'Ready for a St. Petersburg quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does a typical handyman visit cost in St. Petersburg?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined St. Petersburg scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in St. Petersburg?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in St. Petersburg; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach St. Petersburg?', 'Most St. Petersburg requests schedule within one to two business days on existing Pinellas County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "tampa": {
        "hero_lead": 'Handyman repairs in Tampa — registered, insured Safety Harbor crew serving Hyde Park.',
        "meta_description": 'Tampa handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": "Whether you found us online or from a neighbor, Knight Group treats Tampa jobs as neighborhood work — protected floors, labeled hardware, and scope explained before tools start. We route Tampa from Safety Harbor across the bay — prioritizing northwest Tampa, Westchase, Town 'n' Country, and Carrollwood on planned days. South Tampa and far-east addresses are accepted only when they fit that route; confirm the address first.",
        "scheduling": 'Planning a Tampa repair? Knight Group confirms Hillsborough County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: tasks we accept are quoted in writing; anything that needs a licensed trade is flagged before you approve labor.',
        "closing": 'See related service pages, then schedule a Tampa visit. Active leaks should be called in so we can triage licensed-trade needs.',
        "faq_price": ('How much does a typical handyman visit cost in Tampa?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Tampa scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Tampa?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Tampa; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Tampa?', 'Most Tampa requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "town-n-country": {
        "hero_lead": "Handyman repairs in Town 'n' Country — registered, insured Safety Harbor crew serving Countryway.",
        "meta_description": "Town 'n' Country handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.",
        "opening": "Knight Group Handyman Services LLC dispatches from 1225 7th St S in Safety Harbor. Town 'n' Country is on those routes — you reach the local crew, not a franchise call center. Town 'n' Country’s villa HOAs often need discrete, insured vendors for interior repairs — we provide written scope and respect community parking rules on every visit.",
        "scheduling": "Dispatch runs from 1225 7th St S, Safety Harbor 34695. Town 'n' Country jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.",
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": "Explore our {county_link}, browse the Town 'n' Country job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.",
        "faq_price": ("How much does a typical handyman visit cost in Town 'n' Country?", "Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Town 'n' Country scopes can be quoted as a flat rate after photos."),
        "faq_licensed": ("Can Knight Group do plumbing or electrical work in Town 'n' Country?", "Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Town 'n' Country; licensed trades are referred when the law requires it."),
        "faq_schedule": ("How soon can you reach Town 'n' Country?", "Most Town 'n' Country requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed."),
    },
    "westchase": {
        "hero_lead": 'Handyman repairs in Westchase — registered, insured Safety Harbor crew serving Westchase proper.',
        "meta_description": 'Westchase handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Homeowners in Westchase usually want a registered vendor who quotes before work starts. Knight Group routes Hillsborough County from Safety Harbor with honest diagnosis on every visit. Westchase homeowners expect neat work and clean job sites — standard for us. We protect floors, label removed hardware, and leave HOA-visible areas broom-clean before leaving the community gates.',
        "scheduling": "We batch Hillsborough County routes from our Safety Harbor shop. Share address details for Westchase when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Westchase job needs a licensed plumber, electrician, roofer, or permitted contractor, we say so before demolition. Honesty keeps the visit from turning into a change order.',
        "closing": 'Next steps: open the Hillsborough County coverage hub, review handyman services and pricing, or book with photos. Active water — phone first.',
        "faq_price": ('How much does a typical handyman visit cost in Westchase?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Westchase scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Westchase?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Westchase; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Westchase?', 'Most Westchase requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "citrus-park": {
        "hero_lead": 'Handyman repairs in Citrus Park — registered, insured Safety Harbor crew serving Gunn Highway neighborhoods.',
        "meta_description": 'Citrus Park handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": "Looking for reliable handyman help in Citrus Park? Vince Knight's team handles drywall, doors, paint-ready finishing, and punch-list repairs without a two-hour minimum. Citrus Park’s mix of owner-occupied and rental stock near major employers means fast scheduling matters. We confirm whether your job is handyman scope before rolling through Gunn Highway traffic.",
        "scheduling": 'Citrus Park scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Citrus Park visit. Knight Group documents what we can legally perform and refers licensed trades when DBPR or a permit requires it.',
        "closing": 'Look at local proof on our gallery page. Knight Group publishes real Hillsborough County project photos, not stock interiors.',
        "faq_price": ('How much does a typical handyman visit cost in Citrus Park?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Citrus Park scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Citrus Park?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Citrus Park; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Citrus Park?', 'Most Citrus Park requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "carrollwood": {
        "hero_lead": 'Handyman repairs in Carrollwood — registered, insured Safety Harbor crew serving Carrollwood Village.',
        "meta_description": 'Carrollwood handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Carrollwood properties need a contractor who understands local housing stock — not a statewide template page. Knight Group focuses on everyday punch-list work across Hillsborough County. Carrollwood sellers often need a short punch list before photos — we quote flat-rate when the scope is defined and can bundle paint, drywall, and fixture items in one visit.',
        "scheduling": 'Estimates for Carrollwood work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state contractor license. Carrollwood homeowners get a clear line between repairs we handle and trades we coordinate.',
        "closing": 'Ready for a Carrollwood quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does a typical handyman visit cost in Carrollwood?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Carrollwood scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Carrollwood?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Carrollwood; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Carrollwood?', 'Most Carrollwood requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "northdale": {
        "hero_lead": 'Handyman repairs in Northdale — registered, insured Safety Harbor crew serving Northdale Golf Club neighborhoods.',
        "meta_description": 'Northdale handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'From Northdale Golf Club neighborhoods, Knight Group schedules Northdale visits with written estimates and an insured crew crossing Hillsborough County on planned routes. Northdale homeowners often modernize one room at a time — faucet and hardware updates plus paint touch-ups are a natural bundle without opening walls.',
        "scheduling": 'Planning a Northdale repair? Knight Group confirms Hillsborough County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: tasks we accept are quoted in writing; anything that needs a licensed trade is flagged before you approve labor.',
        "closing": 'See related service pages, then schedule a Northdale visit. Active leaks should be called in so we can triage licensed-trade needs.',
        "faq_price": ('How much does a typical handyman visit cost in Northdale?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Northdale scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Northdale?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Northdale; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Northdale?', 'Most Northdale requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "egypt-lake-leto": {
        "hero_lead": 'Handyman repairs in Egypt Lake-Leto — registered, insured Safety Harbor crew serving Egypt Lake.',
        "meta_description": 'Egypt Lake-Leto handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'When storm season stresses doors, screens, and drywall, Egypt Lake-Leto owners call Knight Group for practical repairs that stay inside current Florida handyman limits. Landlords in Egypt Lake-Leto need reliable turnaround times. We batch multi-unit lists when keys align and provide itemized written estimates for owner approval.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Egypt Lake-Leto jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": 'Explore our {county_link}, browse the Egypt Lake-Leto job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.',
        "faq_price": ('How much does a typical handyman visit cost in Egypt Lake-Leto?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Egypt Lake-Leto scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Egypt Lake-Leto?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Egypt Lake-Leto; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Egypt Lake-Leto?', 'Most Egypt Lake-Leto requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "temple-terrace": {
        "hero_lead": 'Handyman repairs in Temple Terrace — registered, insured Safety Harbor crew serving Temple Terrace Estates.',
        "meta_description": 'Temple Terrace handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Knight Group answers Temple Terrace requests with photos-first estimates, flat-rate quotes on defined scopes, and hourly pricing only when punch lists are open-ended. Temple Terrace’s river neighborhoods reward technicians who understand exterior wood repair sequencing — prime, caulk, then paint — so repairs survive the next wet season.',
        "scheduling": "We batch Hillsborough County routes from our Safety Harbor shop. Share address details for Temple Terrace when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Temple Terrace job needs a licensed plumber, electrician, roofer, or permitted contractor, we say so before demolition. Honesty keeps the visit from turning into a change order.',
        "closing": 'Next steps: open the Hillsborough County coverage hub, review handyman services and pricing, or book with photos. Active water — phone first.',
        "faq_price": ('How much does a typical handyman visit cost in Temple Terrace?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Temple Terrace scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Temple Terrace?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Temple Terrace; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Temple Terrace?', 'Most Temple Terrace requests schedule within one to two business days on existing Hillsborough County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "holiday": {
        "hero_lead": 'Handyman repairs in Holiday — registered, insured Safety Harbor crew serving Holiday Lake.',
        "meta_description": 'Holiday handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Holiday homeowners tired of national lead-gen sites choose Knight Group — one Safety Harbor business, one accountable crew. Holiday’s retiree homeowners often want one trusted vendor for a short list — we explain each repair in plain language and leave written notes when family members manage the property remotely.',
        "scheduling": 'Holiday scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Holiday visit. Knight Group documents what we can legally perform and refers licensed trades when DBPR or a permit requires it.',
        "closing": 'Look at local proof on our gallery page. Knight Group publishes real Pasco County project photos, not stock interiors.',
        "faq_price": ('How much does a typical handyman visit cost in Holiday?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Holiday scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Holiday?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Holiday; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Holiday?', 'Most Holiday requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "trinity": {
        "hero_lead": 'Handyman repairs in Trinity — registered, insured Safety Harbor crew serving Trinity Oaks.',
        "meta_description": 'Trinity handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Need a visit in Trinity? Knight Group schedules around existing Pasco County routes so arrival windows stay realistic and drive time does not inflate your quote. Trinity owners often call for one visible repair — a stair hall dent or master bath drip — and add items once trust is established. Written line-item quotes keep that expansion orderly.',
        "scheduling": 'Estimates for Trinity work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state contractor license. Trinity homeowners get a clear line between repairs we handle and trades we coordinate.',
        "closing": 'Ready for a Trinity quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does a typical handyman visit cost in Trinity?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Trinity scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Trinity?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Trinity; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Trinity?', 'Most Trinity requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "new-port-richey": {
        "hero_lead": 'Handyman repairs in New Port Richey — registered, insured Safety Harbor crew serving downtown NPR.',
        "meta_description": 'New Port Richey handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Whether you found us online or from a neighbor, Knight Group treats New Port Richey jobs as neighborhood work — protected floors, labeled hardware, and scope explained before tools start. New Port Richey’s downtown river homes need careful moisture diagnosis before cosmetic patches — we stabilize leaks first, then texture and paint so stains do not return next storm season.',
        "scheduling": 'Planning a New Port Richey repair? Knight Group confirms Pasco County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: tasks we accept are quoted in writing; anything that needs a licensed trade is flagged before you approve labor.',
        "closing": 'See related service pages, then schedule a New Port Richey visit. Active leaks should be called in so we can triage licensed-trade needs.',
        "faq_price": ('How much does a typical handyman visit cost in New Port Richey?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined New Port Richey scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in New Port Richey?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in New Port Richey; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach New Port Richey?', 'Most New Port Richey requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "elfers": {
        "hero_lead": 'Handyman repairs in Elfers — registered, insured Safety Harbor crew serving Elfers Parkway corridor.',
        "meta_description": 'Elfers handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Knight Group Handyman Services LLC dispatches from 1225 7th St S in Safety Harbor. Elfers is on those routes — you reach the local crew, not a franchise call center. Elfers homeowners want straightforward pricing without minimum-job games — we quote defined scopes flat-rate when photos show the full problem.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Elfers jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": 'Explore our {county_link}, browse the Elfers job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.',
        "faq_price": ('How much does a typical handyman visit cost in Elfers?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Elfers scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Elfers?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Elfers; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Elfers?', 'Most Elfers requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "seven-springs": {
        "hero_lead": 'Handyman repairs in Seven Springs — registered, insured Safety Harbor crew serving Seven Springs Boulevard.',
        "meta_description": 'Seven Springs handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Homeowners in Seven Springs usually want a registered vendor who quotes before work starts. Knight Group routes Pasco County from Safety Harbor with honest diagnosis on every visit. Seven Springs’ larger lots mean we confirm tool access and power availability for exterior wood repair — a quick phone call saves a wasted trip down wooded driveways.',
        "scheduling": "We batch Pasco County routes from our Safety Harbor shop. Share address details for Seven Springs when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Seven Springs job needs a licensed plumber, electrician, roofer, or permitted contractor, we say so before demolition. Honesty keeps the visit from turning into a change order.',
        "closing": 'Next steps: open the Pasco County coverage hub, review handyman services and pricing, or book with photos. Active water — phone first.',
        "faq_price": ('How much does a typical handyman visit cost in Seven Springs?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Seven Springs scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Seven Springs?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Seven Springs; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Seven Springs?', 'Most Seven Springs requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "jasmine-estates": {
        "hero_lead": 'Handyman repairs in Jasmine Estates — registered, insured Safety Harbor crew serving Jasmine Boulevard.',
        "meta_description": 'Jasmine Estates handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": "Looking for reliable handyman help in Jasmine Estates? Vince Knight's team handles drywall, doors, paint-ready finishing, and punch-list repairs without a two-hour minimum. Jasmine Estates landlords appreciate itemized invoices — we list each room and task so property managers can allocate costs across units.",
        "scheduling": 'Jasmine Estates scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Jasmine Estates visit. Knight Group documents what we can legally perform and refers licensed trades when DBPR or a permit requires it.',
        "closing": 'Look at local proof on our gallery page. Knight Group publishes real Pasco County project photos, not stock interiors.',
        "faq_price": ('How much does a typical handyman visit cost in Jasmine Estates?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Jasmine Estates scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Jasmine Estates?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Jasmine Estates; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Jasmine Estates?', 'Most Jasmine Estates requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "beacon-square": {
        "hero_lead": 'Handyman repairs in Beacon Square — registered, insured Safety Harbor crew serving Beacon Square Drive loops and US-19 frontage streets.',
        "meta_description": 'Beacon Square handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'Beacon Square properties need a contractor who understands local housing stock — not a statewide template page. Knight Group focuses on everyday punch-list work across Pasco County. Beacon Square repairs are often budget-sensitive — we separate must-fix items from cosmetic upgrades so owners can phase work.',
        "scheduling": 'Estimates for Beacon Square work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state contractor license. Beacon Square homeowners get a clear line between repairs we handle and trades we coordinate.',
        "closing": 'Ready for a Beacon Square quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does a typical handyman visit cost in Beacon Square?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Beacon Square scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Beacon Square?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Beacon Square; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Beacon Square?', 'Most Beacon Square requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "port-richey": {
        "hero_lead": 'Handyman repairs in Port Richey — registered, insured Safety Harbor crew serving downtown Port Richey.',
        "meta_description": 'Port Richey handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.',
        "opening": 'From downtown Port Richey, Knight Group schedules Port Richey visits with written estimates and an insured crew crossing Pasco County on planned routes. Port Richey’s river and Gulf edges mean we carry corrosion-resistant hardware options when replacing rollers and screen corners — small detail that extends the repair.',
        "scheduling": 'Planning a Port Richey repair? Knight Group confirms Pasco County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: tasks we accept are quoted in writing; anything that needs a licensed trade is flagged before you approve labor.',
        "closing": 'See related service pages, then schedule a Port Richey visit. Active leaks should be called in so we can triage licensed-trade needs.',
        "faq_price": ('How much does a typical handyman visit cost in Port Richey?', 'Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Port Richey scopes can be quoted as a flat rate after photos.'),
        "faq_licensed": ('Can Knight Group do plumbing or electrical work in Port Richey?', 'Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Port Richey; licensed trades are referred when the law requires it.'),
        "faq_schedule": ('How soon can you reach Port Richey?', 'Most Port Richey requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed.'),
    },
    "land-o-lakes": {
        "hero_lead": "Handyman repairs in Land O' Lakes — registered, insured Safety Harbor crew serving Connerton.",
        "meta_description": "Land O' Lakes handyman: drywall, doors, paint-ready finish work, and punch-list repairs from Safety Harbor. Registered and insured. Free estimate.",
        "opening": "When storm season stresses doors, screens, and drywall, Land O' Lakes owners call Knight Group for practical repairs that stay inside current Florida handyman limits. Land O' Lakes grew fast — many owners are hitting the first decade of fixture failures and kid-related drywall damage. We help prioritize what matters for resale vs. daily living.",
        "scheduling": "Dispatch runs from 1225 7th St S, Safety Harbor 34695. Land O' Lakes jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.",
        "scope_note": 'Allowed work includes drywall, paint, interior doors, screens, hardware, caulk, and punch-list repairs. Electrical connection work and plumbing that taps drinking water require licensed trades — we diagnose first.',
        "closing": "Explore our {county_link}, browse the Land O' Lakes job list above, and see matching work in our project gallery. Active leaks — call, do not wait on email.",
        "faq_price": ("How much does a typical handyman visit cost in Land O' Lakes?", "Standard visits are $150 for the first hour and $75 each additional hour, with no two-hour minimum. Defined Land O' Lakes scopes can be quoted as a flat rate after photos."),
        "faq_licensed": ("Can Knight Group do plumbing or electrical work in Land O' Lakes?", "Florida requires a DBPR license for electrical connection work and for plumbing that connects to drinking water. Vince Knight’s journeyman plumbing background helps diagnose the issue in Land O' Lakes; licensed trades are referred when the law requires it."),
        "faq_schedule": ("How soon can you reach Land O' Lakes?", "Most Land O' Lakes requests schedule within one to two business days on existing Pasco County routes. Active leaks should be called in at (813) 649-3341 so we can triage and involve a licensed plumber when needed."),
    },
}

COUNTY_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "pinellas": {
        "hero_lead": 'Pinellas County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'Pinellas County handyman routes from Safety Harbor: drywall, doors, paint-ready finish work. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers Pinellas County on daily routes from Safety Harbor. Homeowners get a local insured crew for drywall, doors, carpentry, painting touch-ups, and punch-list repairs — not a referral marketplace. Licensed trades are coordinated when Florida DBPR requires it.',
        "scheduling": 'Book Pinellas County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Pinellas County. Licensed trades are referred for electrical connection work, plumbing that taps drinking water, roofing, new windows, structural additions, and mold remediation over 10 square feet.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Pinellas County proof. Emergency leaks — call first.',
    },
    "hillsborough": {
        "hero_lead": 'Hillsborough County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'Hillsborough County handyman routes from Safety Harbor: drywall, doors, paint-ready finish work. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers northwest Hillsborough on scheduled and expanding routes from Safety Harbor. Homeowners get a local insured crew for drywall, doors, carpentry, painting touch-ups, and punch-list repairs — not a referral marketplace. Licensed trades are coordinated when Florida DBPR requires it. Address confirmation is required; this is not a daily Pinellas-style loop across the whole county.',
        "scheduling": 'Book Hillsborough County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Hillsborough County. Licensed trades are referred for electrical connection work, plumbing that taps drinking water, roofing, new windows, structural additions, and mold remediation over 10 square feet.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Hillsborough County proof. Emergency leaks — call first.',
    },
    "pasco": {
        "hero_lead": 'Pasco County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'Pasco County handyman routes from Safety Harbor: drywall, doors, paint-ready finish work. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers west Pasco on scheduled route days from Safety Harbor. Homeowners get a local insured crew for drywall, doors, carpentry, painting touch-ups, and punch-list repairs — not a referral marketplace. Licensed trades are coordinated when Florida DBPR requires it. This is expanding coverage with address confirmation — not a daily county-wide loop.',
        "scheduling": 'Book Pasco County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Pasco County. Licensed trades are referred for electrical connection work, plumbing that taps drinking water, roofing, new windows, structural additions, and mold remediation over 10 square feet.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Pasco County proof. Emergency leaks — call first.',
    },
}

COMBO_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "clearwater-sink-repair": {
        "hero_lead": 'Sink And Faucet Repair in Clearwater — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Sink And Faucet Repair in Clearwater: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for sink and faucet repair in Clearwater should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Clearwater from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary sink and faucet repair task, we sequence drywall, caulk, or paint so Clearwater homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Clearwater sink and faucet repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "clearwater-drywall-repair": {
        "hero_lead": 'Drywall Repair in Clearwater — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Drywall Repair in Clearwater: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for drywall repair in Clearwater should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Clearwater from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary drywall repair task, we sequence drywall, caulk, or paint so Clearwater homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Clearwater drywall repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "safety-harbor-home-repair": {
        "hero_lead": 'Home Repair in Safety Harbor — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Home Repair in Safety Harbor: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for home repair in Safety Harbor should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Safety Harbor from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary home repair task, we sequence drywall, caulk, or paint so Safety Harbor homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Safety Harbor home repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "palm-harbor-drywall-repair": {
        "hero_lead": 'Drywall Repair in Palm Harbor — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Drywall Repair in Palm Harbor: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for drywall repair in Palm Harbor should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Palm Harbor from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary drywall repair task, we sequence drywall, caulk, or paint so Palm Harbor homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Palm Harbor drywall repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "largo-toilet-repair": {
        "hero_lead": 'Toilet Repair in Largo — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Toilet Repair in Largo: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for toilet repair in Largo should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Largo from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary toilet repair task, we sequence drywall, caulk, or paint so Largo homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Largo toilet repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "oldsmar-door-adjustment": {
        "hero_lead": 'Door Adjustment in Oldsmar — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Door Adjustment in Oldsmar: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for door adjustment in Oldsmar should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Oldsmar from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary door adjustment task, we sequence drywall, caulk, or paint so Oldsmar homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Oldsmar door adjustment with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "dunedin-trim-repair": {
        "hero_lead": 'Trim Repair in Dunedin — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Trim Repair in Dunedin: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for trim repair in Dunedin should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Dunedin from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary trim repair task, we sequence drywall, caulk, or paint so Dunedin homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Dunedin trim repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "seminole-interior-painting": {
        "hero_lead": 'Interior Painting in Seminole — written estimates and paint-ready finish work from Safety Harbor.',
        "meta_description": 'Interior Painting in Seminole: documented scope, registered and insured Safety Harbor crew. Free written estimate.',
        "opening": 'Searches for interior painting in Seminole should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Seminole from Safety Harbor with documented scope on real homes.',
        "follow_through": 'After the primary interior painting task, we sequence drywall, caulk, or paint so Seminole homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Seminole interior painting with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
}


def city_copy(slug: str) -> dict:
    return dict(CITY_PAGE_COPY.get(slug, {}))


def county_copy(slug: str) -> dict:
    return dict(COUNTY_PAGE_COPY.get(slug, {}))


def combo_copy(slug: str) -> dict:
    return dict(COMBO_PAGE_COPY.get(slug, {}))
