"""Unique SEO copy for geo pages — Serper-informed, non-duplicated across cities."""

from __future__ import annotations

CITY_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "safety-harbor": {
        "hero_lead": 'Knight Group Handyman in Safety Harbor — registered, insured Safety Harbor crew serving downtown.',
        "meta_description": 'Safety Harbor knight group handyman: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Knight Group Handyman Services LLC is headquartered on 7th Street South in Safety Harbor — when you search knight group handyman, you reach the actual local crew, not a franchise call center. Same-day routing is easiest here, and Vince Knight knows the mix of older downtown stock and newer infill along McMullen-Booth.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Safety Harbor jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": 'Explore our {county_link}, browse the Safety Harbor job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.',
        "faq_price": ('How much does knight group handyman cost in Safety Harbor?', 'Pricing depends on access, parts, and finish work. Defined Safety Harbor scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Safety Harbor?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Safety Harbor. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Safety Harbor for handyman pinellas county?', 'Most Safety Harbor requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "clearwater": {
        "hero_lead": 'Clearwater Handyman in Clearwater — registered, insured Safety Harbor crew serving Island Estates.',
        "meta_description": 'Clearwater Handyman: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Homeowners comparing clearwater handyman options in Clearwater want a registered vendor who quotes before work starts. Knight Group routes Pinellas County from Safety Harbor with journeyman-level fixture diagnosis on every visit. Clearwater owners often juggle tenant turnovers near the beach and owner-occupied repairs inland. We batch Countryside and Coachman routes with beach condo stops when access windows align — one crew, one estimate, no franchise call center.',
        "scheduling": "We batch Pinellas County routes from our Safety Harbor shop. Share address details for Clearwater when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Clearwater job needs a licensed plumber, electrician, or permitted contractor, we say so on site before demolition. That honesty keeps clearwater handyman searches from turning into change orders.',
        "closing": 'Next steps: open the Pinellas County coverage hub, review handyman services and pricing, or book with photos. Emergency water — phone first.',
        "faq_price": ('How much does clearwater handyman cost in Clearwater?', 'Pricing depends on access, parts, and finish work. Defined Clearwater scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Clearwater?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Clearwater. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Clearwater for sink repair clearwater?', 'Most Clearwater requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "dunedin": {
        "hero_lead": 'Handyman Company Pinellas in Dunedin — registered, insured Safety Harbor crew serving downtown Dunedin.',
        "meta_description": 'Dunedin handyman company pinellas: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": "Looking for reliable handyman company pinellas help in Dunedin? Vince Knight's team handles drywall, doors, fixture plumbing, and paint-ready finishing without minimum-job games. Dunedin’s walkable downtown and tight lot lines mean access and parking matter. We plan material carries and protect historic trim profiles when patching — important for homeowners who value the town’s craftsman character.",
        "scheduling": 'Dunedin scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Dunedin visit. Knight Group documents what we can legally perform and refers licensed trades when permits or specialty licenses apply.',
        "closing": 'Compare handyman company pinellas providers, then look at local proof on our gallery page. Knight Group publishes real Pinellas County project photos, not stock interiors.',
        "faq_price": ('How much does handyman company pinellas cost in Dunedin?', 'Pricing depends on access, parts, and finish work. Defined Dunedin scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Dunedin?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Dunedin. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Dunedin for handyman company pinellas?', 'Most Dunedin requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "palm-harbor": {
        "hero_lead": 'Handyman Pinellas County in Palm Harbor — registered, insured Safety Harbor crew serving East Lake.',
        "meta_description": 'Palm Harbor handyman pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Palm Harbor properties need a handyman who understands local housing stock — not a statewide template page. Knight Group focuses on handyman pinellas county fl and everyday punch-list work across Pinellas County. East Lake and Highland Lakes homeowners often call for one bathroom issue and discover a short punch list while we are on site. We document each item and quote before expanding scope — common in larger Palm Harbor homes with multiple wet walls.',
        "scheduling": 'Estimates for Palm Harbor work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state license beyond handyman scope. Palm Harbor homeowners get a clear line between fixture repairs we handle and trades we coordinate out.',
        "closing": 'Ready for a Palm Harbor quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does handyman pinellas county cost in Palm Harbor?', 'Pricing depends on access, parts, and finish work. Defined Palm Harbor scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Palm Harbor?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Palm Harbor. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Palm Harbor for handyman pinellas county fl?', 'Most Palm Harbor requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "largo": {
        "hero_lead": 'Handyman Pinellas County Fl in Largo — registered, insured Safety Harbor crew serving Bardmoor.',
        "meta_description": 'Largo handyman pinellas county fl: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'From Bardmoor, Knight Group delivers handyman pinellas county fl service with written estimates and insured crews crossing Pinellas County on planned routes. Largo’s central Pinellas location makes it a natural mid-route stop between Safety Harbor and the beaches. We schedule Bardmoor and Ridgecrest blocks together to keep drive time low and arrival windows tight.',
        "scheduling": 'Planning a Largo repair? Knight Group confirms Pinellas County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: handyman near me small jobs tasks we accept are quoted in writing; anything outside handyman limits is flagged before you approve labor.',
        "closing": 'See how we handle handyman near me small jobs on service detail pages, then schedule a Largo visit. Active leaks should be called in directly for priority routing.',
        "faq_price": ('How much does handyman pinellas county fl cost in Largo?', 'Pricing depends on access, parts, and finish work. Defined Largo scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Largo?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Largo. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Largo for handyman near me small jobs?', 'Most Largo requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "oldsmar": {
        "hero_lead": 'Handyman Near Me Small Jobs in Oldsmar — registered, insured Safety Harbor crew serving East Lake Woodlands edge.',
        "meta_description": 'Oldsmar handyman near me small jobs: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'When door repair pinellas county searches spike after storm season, Oldsmar owners call Knight Group for practical repairs that stay in handyman scope. Oldsmar sits on our daily route between Hillsborough jobs and central Pinellas. Homeowners here benefit from a team that already crosses the bay — not a contractor who treats Oldsmar as out of territory.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Oldsmar jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": 'Explore our {county_link}, browse the Oldsmar job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.',
        "faq_price": ('How much does handyman near me small jobs cost in Oldsmar?', 'Pricing depends on access, parts, and finish work. Defined Oldsmar scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Oldsmar?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Oldsmar. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Oldsmar for door repair pinellas county?', 'Most Oldsmar requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "tarpon-springs": {
        "hero_lead": 'Plumbing Services In Pinellas County in Tarpon Springs — registered, insured Safety Harbor crew serving historic district.',
        "meta_description": 'Tarpon Springs plumbing services in pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Knight Group answers plumbing services in pinellas county requests across Tarpon Springs with photos-first estimates, flat-rate quotes on defined scopes, and hourly pricing only when punch lists are open-ended. Tarpon Springs’ older housing stock rewards technicians who understand tight wet walls and fragile tile. Vince Knight’s plumbing background helps diagnose whether a leak stays handyman scope or needs a licensed repipe referral.',
        "scheduling": "We batch Pinellas County routes from our Safety Harbor shop. Share address details for Tarpon Springs when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Tarpon Springs job needs a licensed plumber, electrician, or permitted contractor, we say so on site before demolition. That honesty keeps plumbing services in pinellas county searches from turning into change orders.',
        "closing": 'Next steps: open the Pinellas County coverage hub, review handyman services and pricing, or book with photos. Emergency water — phone first.',
        "faq_price": ('How much does plumbing services in pinellas county cost in Tarpon Springs?', 'Pricing depends on access, parts, and finish work. Defined Tarpon Springs scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Tarpon Springs?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Tarpon Springs. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Tarpon Springs for plumbing repair clearwater fl?', 'Most Tarpon Springs requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "seminole": {
        "hero_lead": 'Handyman Painting Pinellas County in Seminole — registered, insured Safety Harbor crew serving Park Boulevard corridor.',
        "meta_description": 'Seminole handyman painting pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Seminole homeowners tired of national lead-gen sites choose Knight Group for handyman painting pinellas county — one Safety Harbor business, one accountable crew. Seminole homeowners along Park Boulevard often need paint-ready drywall repair after humidity stains — we sequence primer, texture, and topcoat so patches do not flash under afternoon sun.',
        "scheduling": 'Seminole scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Seminole visit. Knight Group documents what we can legally perform and refers licensed trades when permits or specialty licenses apply.',
        "closing": 'Compare handyman painting pinellas county providers, then look at local proof on our gallery page. Knight Group publishes real Pinellas County project photos, not stock interiors.',
        "faq_price": ('How much does handyman painting pinellas county cost in Seminole?', 'Pricing depends on access, parts, and finish work. Defined Seminole scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Seminole?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Seminole. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Seminole for handyman painting pinellas county?', 'Most Seminole requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "st-petersburg": {
        "hero_lead": 'Handyman Services Pinellas County in St. Petersburg — registered, insured Safety Harbor crew serving Kenwood.',
        "meta_description": 'St. Petersburg handyman services pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Need handyman services pinellas county today? Knight Group schedules St. Petersburg visits around existing Pinellas County routes so arrival windows stay realistic and drive time does not inflate your quote. St. Pete’s neighborhood variety means we confirm access, parking, and scope before dispatch — a Kenwood bungalow repair differs from a Tyrone condo turnover. Photos through our booking form speed that conversation.',
        "scheduling": 'Estimates for St. Petersburg work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state license beyond handyman scope. St. Petersburg homeowners get a clear line between fixture repairs we handle and trades we coordinate out.',
        "closing": 'Ready for a St. Petersburg quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does handyman services pinellas county cost in St. Petersburg?', 'Pricing depends on access, parts, and finish work. Defined St. Petersburg scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in St. Petersburg?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in St. Petersburg. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach St. Petersburg for handyman projects pinellas county?', 'Most St. Petersburg requests schedule within one to two business days on existing Pinellas County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "tampa": {
        "hero_lead": 'Handyman Near Me Small Jobs in Tampa — registered, insured Safety Harbor crew serving Hyde Park.',
        "meta_description": 'Tampa handyman near me small jobs: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Whether you found us through handyman near me small jobs or handyman tampa fl, Knight Group treats Tampa jobs as neighborhood work — protected floors, labeled hardware, and scope explained before tools start. We route Tampa from Safety Harbor across the bay — prioritizing South Tampa and Westshore clusters on planned days rather than random cross-county zigzags. That keeps estimates honest and arrival windows realistic.',
        "scheduling": 'Planning a Tampa repair? Knight Group confirms Hillsborough County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: handyman tampa fl tasks we accept are quoted in writing; anything outside handyman limits is flagged before you approve labor.',
        "closing": 'See how we handle handyman tampa fl on service detail pages, then schedule a Tampa visit. Active leaks should be called in directly for priority routing.',
        "faq_price": ('How much does handyman near me small jobs cost in Tampa?', 'Pricing depends on access, parts, and finish work. Defined Tampa scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Tampa?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Tampa. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Tampa for handyman tampa fl?', 'Most Tampa requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "town-n-country": {
        "hero_lead": "Handyman Near Me Small Jobs in Town 'n' Country — registered, insured Safety Harbor crew serving Countryway.",
        "meta_description": "Town 'n' Country handyman near me small jobs: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.",
        "opening": "Knight Group Handyman Services LLC is headquartered on 7th Street South in Town 'n' Country — when you search handyman near me small jobs, you reach the actual local crew, not a franchise call center. Town 'n' Country’s villa HOAs often need discrete, insured vendors for interior repairs — we provide written scope and respect community parking rules on every visit.",
        "scheduling": "Dispatch runs from 1225 7th St S, Safety Harbor 34695. Town 'n' Country jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.",
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": "Explore our {county_link}, browse the Town 'n' Country job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.",
        "faq_price": ("How much does handyman near me small jobs cost in Town 'n' Country?", "Pricing depends on access, parts, and finish work. Defined Town 'n' Country scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit."),
        "faq_licensed": ("Can a handyman do plumbing or electrical work in Town 'n' Country?", "Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Town 'n' Country. Work requiring a licensed plumber, electrician, or permit is referred before tools come out."),
        "faq_schedule": ("How fast can you reach Town 'n' Country for handyman tampa fl?", "Most Town 'n' Country requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly."),
    },
    "westchase": {
        "hero_lead": 'Small Home Renovations Pinellas County in Westchase — registered, insured Safety Harbor crew serving Westchase proper.',
        "meta_description": 'Westchase small home renovations pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Homeowners comparing small home renovations pinellas county options in Westchase want a registered vendor who quotes before work starts. Knight Group routes Hillsborough County from Safety Harbor with journeyman-level fixture diagnosis on every visit. Westchase homeowners expect neat work and clean job sites — standard for us. We protect floors, label removed hardware, and leave HOA-visible areas broom-clean before leaving the community gates.',
        "scheduling": "We batch Hillsborough County routes from our Safety Harbor shop. Share address details for Westchase when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Westchase job needs a licensed plumber, electrician, or permitted contractor, we say so on site before demolition. That honesty keeps small home renovations pinellas county searches from turning into change orders.',
        "closing": 'Next steps: open the Hillsborough County coverage hub, review handyman services and pricing, or book with photos. Emergency water — phone first.',
        "faq_price": ('How much does small home renovations pinellas county cost in Westchase?', 'Pricing depends on access, parts, and finish work. Defined Westchase scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Westchase?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Westchase. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Westchase for handyman westchase fl?', 'Most Westchase requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "citrus-park": {
        "hero_lead": 'General Home Repairs Pinellas in Citrus Park — registered, insured Safety Harbor crew serving Gunn Highway neighborhoods.',
        "meta_description": 'Citrus Park general home repairs pinellas: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": "Looking for reliable general home repairs pinellas help in Citrus Park? Vince Knight's team handles drywall, doors, fixture plumbing, and paint-ready finishing without minimum-job games. Citrus Park’s mix of owner-occupied and rental stock near major employers means fast scheduling matters. We confirm whether your job is handyman scope before rolling through Gunn Highway traffic.",
        "scheduling": 'Citrus Park scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Citrus Park visit. Knight Group documents what we can legally perform and refers licensed trades when permits or specialty licenses apply.',
        "closing": 'Compare general home repairs pinellas providers, then look at local proof on our gallery page. Knight Group publishes real Hillsborough County project photos, not stock interiors.',
        "faq_price": ('How much does general home repairs pinellas cost in Citrus Park?', 'Pricing depends on access, parts, and finish work. Defined Citrus Park scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Citrus Park?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Citrus Park. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Citrus Park for handyman citrus park fl?', 'Most Citrus Park requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "carrollwood": {
        "hero_lead": 'Handyman Near Me Small Jobs in Carrollwood — registered, insured Safety Harbor crew serving Carrollwood Village.',
        "meta_description": 'Carrollwood handyman near me small jobs: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Carrollwood properties need a handyman who understands local housing stock — not a statewide template page. Knight Group focuses on handyman carrollwood fl and everyday punch-list work across Hillsborough County. Carrollwood sellers often need a short punch list before photos — we quote flat-rate when the scope is defined and can bundle paint, drywall, and fixture items in one visit.',
        "scheduling": 'Estimates for Carrollwood work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state license beyond handyman scope. Carrollwood homeowners get a clear line between fixture repairs we handle and trades we coordinate out.',
        "closing": 'Ready for a Carrollwood quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does handyman near me small jobs cost in Carrollwood?', 'Pricing depends on access, parts, and finish work. Defined Carrollwood scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Carrollwood?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Carrollwood. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Carrollwood for handyman carrollwood fl?', 'Most Carrollwood requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "northdale": {
        "hero_lead": 'Handyman Painting Pinellas County in Northdale — registered, insured Safety Harbor crew serving Northdale Golf Club neighborhoods.',
        "meta_description": 'Northdale handyman painting pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'From Northdale Golf Club neighborhoods, Knight Group delivers handyman painting pinellas county service with written estimates and insured crews crossing Hillsborough County on planned routes. Northdale homeowners often modernize one room at a time — faucet and hardware updates plus paint touch-ups are a natural bundle without opening walls.',
        "scheduling": 'Planning a Northdale repair? Knight Group confirms Hillsborough County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: handyman northdale fl tasks we accept are quoted in writing; anything outside handyman limits is flagged before you approve labor.',
        "closing": 'See how we handle handyman northdale fl on service detail pages, then schedule a Northdale visit. Active leaks should be called in directly for priority routing.',
        "faq_price": ('How much does handyman painting pinellas county cost in Northdale?', 'Pricing depends on access, parts, and finish work. Defined Northdale scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Northdale?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Northdale. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Northdale for handyman northdale fl?', 'Most Northdale requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "egypt-lake-leto": {
        "hero_lead": 'Emergency Handyman Pinellas County in Egypt Lake-Leto — registered, insured Safety Harbor crew serving Egypt Lake.',
        "meta_description": 'Egypt Lake-Leto emergency handyman pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'When landlord handyman tampa searches spike after storm season, Egypt Lake-Leto owners call Knight Group for practical repairs that stay in handyman scope. Landlords in Egypt Lake-Leto need reliable turnaround times. We batch multi-unit lists when keys align and provide itemized written estimates for owner approval.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Egypt Lake-Leto jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": 'Explore our {county_link}, browse the Egypt Lake-Leto job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.',
        "faq_price": ('How much does emergency handyman pinellas county cost in Egypt Lake-Leto?', 'Pricing depends on access, parts, and finish work. Defined Egypt Lake-Leto scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Egypt Lake-Leto?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Egypt Lake-Leto. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Egypt Lake-Leto for landlord handyman tampa?', 'Most Egypt Lake-Leto requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "temple-terrace": {
        "hero_lead": 'Carpentry Services Near Me in Temple Terrace — registered, insured Safety Harbor crew serving Temple Terrace Estates.',
        "meta_description": 'Temple Terrace carpentry services near me: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Knight Group answers carpentry services near me requests across Temple Terrace with photos-first estimates, flat-rate quotes on defined scopes, and hourly pricing only when punch lists are open-ended. Temple Terrace’s river neighborhoods reward technicians who understand exterior wood repair sequencing — prime, caulk, then paint — so repairs survive the next wet season.',
        "scheduling": "We batch Hillsborough County routes from our Safety Harbor shop. Share address details for Temple Terrace when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Temple Terrace job needs a licensed plumber, electrician, or permitted contractor, we say so on site before demolition. That honesty keeps carpentry services near me searches from turning into change orders.',
        "closing": 'Next steps: open the Hillsborough County coverage hub, review handyman services and pricing, or book with photos. Emergency water — phone first.',
        "faq_price": ('How much does carpentry services near me cost in Temple Terrace?', 'Pricing depends on access, parts, and finish work. Defined Temple Terrace scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Temple Terrace?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Temple Terrace. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Temple Terrace for handyman temple terrace fl?', 'Most Temple Terrace requests schedule within one to two business days on existing Hillsborough County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "holiday": {
        "hero_lead": 'Plumbing Services In Pinellas County in Holiday — registered, insured Safety Harbor crew serving Holiday Lake.',
        "meta_description": 'Holiday plumbing services in pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Holiday homeowners tired of national lead-gen sites choose Knight Group for handyman holiday fl — one Safety Harbor business, one accountable crew. Holiday’s retiree homeowners often want one trusted vendor for a short list — we explain each repair in plain language and leave written notes when family members manage the property remotely.',
        "scheduling": 'Holiday scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Holiday visit. Knight Group documents what we can legally perform and refers licensed trades when permits or specialty licenses apply.',
        "closing": 'Compare plumbing services in pinellas county providers, then look at local proof on our gallery page. Knight Group publishes real Pasco County project photos, not stock interiors.',
        "faq_price": ('How much does plumbing services in pinellas county cost in Holiday?', 'Pricing depends on access, parts, and finish work. Defined Holiday scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Holiday?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Holiday. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Holiday for handyman holiday fl?', 'Most Holiday requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "trinity": {
        "hero_lead": 'Handyman Estimate Pinellas County in Trinity — registered, insured Safety Harbor crew serving Trinity Oaks.',
        "meta_description": 'Trinity handyman estimate pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Need handyman estimate pinellas county today? Knight Group schedules Trinity visits around existing Pasco County routes so arrival windows stay realistic and drive time does not inflate your quote. Trinity owners often call for one visible repair — a stair hall dent or master bath drip — and add items once trust is established. Written line-item quotes keep that expansion orderly.',
        "scheduling": 'Estimates for Trinity work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state license beyond handyman scope. Trinity homeowners get a clear line between fixture repairs we handle and trades we coordinate out.',
        "closing": 'Ready for a Trinity quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does handyman estimate pinellas county cost in Trinity?', 'Pricing depends on access, parts, and finish work. Defined Trinity scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Trinity?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Trinity. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Trinity for handyman trinity fl?', 'Most Trinity requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "new-port-richey": {
        "hero_lead": 'Plumbing Repair Clearwater Fl in New Port Richey — registered, insured Safety Harbor crew serving downtown NPR.',
        "meta_description": 'New Port Richey plumbing repair clearwater fl: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Whether you found us through plumbing repair clearwater fl or handyman new port richey fl, Knight Group treats New Port Richey jobs as neighborhood work — protected floors, labeled hardware, and scope explained before tools start. New Port Richey’s downtown river homes need careful moisture diagnosis before cosmetic patches — we stabilize leaks first, then texture and paint so stains do not return next storm season.',
        "scheduling": 'Planning a New Port Richey repair? Knight Group confirms Pasco County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: handyman new port richey fl tasks we accept are quoted in writing; anything outside handyman limits is flagged before you approve labor.',
        "closing": 'See how we handle handyman new port richey fl on service detail pages, then schedule a New Port Richey visit. Active leaks should be called in directly for priority routing.',
        "faq_price": ('How much does plumbing repair clearwater fl cost in New Port Richey?', 'Pricing depends on access, parts, and finish work. Defined New Port Richey scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in New Port Richey?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in New Port Richey. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach New Port Richey for handyman new port richey fl?', 'Most New Port Richey requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "elfers": {
        "hero_lead": 'Handyman Near Me Small Jobs in Elfers — registered, insured Safety Harbor crew serving Elfers Parkway corridor.',
        "meta_description": 'Elfers handyman near me small jobs: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Knight Group Handyman Services LLC is headquartered on 7th Street South in Elfers — when you search handyman near me small jobs, you reach the actual local crew, not a franchise call center. Elfers homeowners want straightforward pricing without minimum-job games — we quote defined scopes flat-rate when photos show the full problem.',
        "scheduling": 'Dispatch runs from 1225 7th St S, Safety Harbor 34695. Elfers jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.',
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": 'Explore our {county_link}, browse the Elfers job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.',
        "faq_price": ('How much does handyman near me small jobs cost in Elfers?', 'Pricing depends on access, parts, and finish work. Defined Elfers scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Elfers?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Elfers. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Elfers for handyman elfers fl?', 'Most Elfers requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "seven-springs": {
        "hero_lead": 'Carpenter Pinellas County in Seven Springs — registered, insured Safety Harbor crew serving Seven Springs Boulevard.',
        "meta_description": 'Seven Springs carpenter pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Homeowners comparing carpenter pinellas county options in Seven Springs want a registered vendor who quotes before work starts. Knight Group routes Pasco County from Safety Harbor with journeyman-level fixture diagnosis on every visit. Seven Springs’ larger lots mean we confirm tool access and power availability for exterior wood repair — a quick phone call saves a wasted trip down wooded driveways.',
        "scheduling": "We batch Pasco County routes from our Safety Harbor shop. Share address details for Seven Springs when booking so we confirm fit on the current week's path.",
        "scope_note": 'If your Seven Springs job needs a licensed plumber, electrician, or permitted contractor, we say so on site before demolition. That honesty keeps carpenter pinellas county searches from turning into change orders.',
        "closing": 'Next steps: open the Pasco County coverage hub, review handyman services and pricing, or book with photos. Emergency water — phone first.',
        "faq_price": ('How much does carpenter pinellas county cost in Seven Springs?', 'Pricing depends on access, parts, and finish work. Defined Seven Springs scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Seven Springs?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Seven Springs. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Seven Springs for handyman seven springs fl?', 'Most Seven Springs requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "jasmine-estates": {
        "hero_lead": 'Handyman Painting Pinellas County in Jasmine Estates — registered, insured Safety Harbor crew serving Jasmine Boulevard.',
        "meta_description": 'Jasmine Estates handyman painting pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": "Looking for reliable handyman painting pinellas county help in Jasmine Estates? Vince Knight's team handles drywall, doors, fixture plumbing, and paint-ready finishing without minimum-job games. Jasmine Estates landlords appreciate itemized invoices — we list each room and task so property managers can allocate costs across units.",
        "scheduling": 'Jasmine Estates scheduling starts with photos through our booking form. For urgent fixture leaks, call (813) 649-3341 — we prioritize active water over standard punch lists.',
        "scope_note": 'Florida handyman rules matter on every Jasmine Estates visit. Knight Group documents what we can legally perform and refers licensed trades when permits or specialty licenses apply.',
        "closing": 'Compare handyman painting pinellas county providers, then look at local proof on our gallery page. Knight Group publishes real Pasco County project photos, not stock interiors.',
        "faq_price": ('How much does handyman painting pinellas county cost in Jasmine Estates?', 'Pricing depends on access, parts, and finish work. Defined Jasmine Estates scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Jasmine Estates?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Jasmine Estates. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Jasmine Estates for handyman jasmine estates fl?', 'Most Jasmine Estates requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "beacon-square": {
        "hero_lead": 'General Home Repairs Pinellas in Beacon Square — registered, insured Safety Harbor crew serving Beacon Square Drive loops and US-19 frontage streets.',
        "meta_description": 'Beacon Square general home repairs pinellas: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'Beacon Square properties need a handyman who understands local housing stock — not a statewide template page. Knight Group focuses on handyman beacon square fl and everyday punch-list work across Pasco County. Beacon Square repairs are often budget-sensitive — we separate must-fix items from cosmetic upgrades so owners can phase work.',
        "scheduling": 'Estimates for Beacon Square work are always written before tools come out. Upload pictures, list rooms affected, and we reply with flat-rate or hourly options as scope allows.',
        "scope_note": 'We do not perform work that requires a state license beyond handyman scope. Beacon Square homeowners get a clear line between fixture repairs we handle and trades we coordinate out.',
        "closing": 'Ready for a Beacon Square quote? Visit the booking form, pricing hub, or {county_link} for neighboring communities served on the same routes.',
        "faq_price": ('How much does general home repairs pinellas cost in Beacon Square?', 'Pricing depends on access, parts, and finish work. Defined Beacon Square scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Beacon Square?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Beacon Square. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Beacon Square for handyman beacon square fl?', 'Most Beacon Square requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "port-richey": {
        "hero_lead": 'Door Repair Pinellas County in Port Richey — registered, insured Safety Harbor crew serving downtown Port Richey.',
        "meta_description": 'Port Richey door repair pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.',
        "opening": 'From downtown Port Richey, Knight Group delivers door repair pinellas county service with written estimates and insured crews crossing Pasco County on planned routes. Port Richey’s river and Gulf edges mean we carry corrosion-resistant hardware options when replacing rollers and screen corners — small detail that extends the repair.',
        "scheduling": 'Planning a Port Richey repair? Knight Group confirms Pasco County routing first, then locks an arrival window. Weekend and after-hours slots are for emergency calls only.',
        "scope_note": 'Scope stays transparent: handyman port richey fl tasks we accept are quoted in writing; anything outside handyman limits is flagged before you approve labor.',
        "closing": 'See how we handle handyman port richey fl on service detail pages, then schedule a Port Richey visit. Active leaks should be called in directly for priority routing.',
        "faq_price": ('How much does door repair pinellas county cost in Port Richey?', 'Pricing depends on access, parts, and finish work. Defined Port Richey scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit.'),
        "faq_licensed": ('Can a handyman do plumbing or electrical work in Port Richey?', 'Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Port Richey. Work requiring a licensed plumber, electrician, or permit is referred before tools come out.'),
        "faq_schedule": ('How fast can you reach Port Richey for handyman port richey fl?', 'Most Port Richey requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly.'),
    },
    "land-o-lakes": {
        "hero_lead": "Handyman Estimate Pinellas County in Land O' Lakes — registered, insured Safety Harbor crew serving Connerton.",
        "meta_description": "Land O' Lakes handyman estimate pinellas county: drywall, fixture plumbing, doors and punch-list repairs. Registered and insured. Free estimate.",
        "opening": "When handyman land o lakes fl searches spike after storm season, Land O' Lakes owners call Knight Group for practical repairs that stay in handyman scope. Land O' Lakes grew fast — many owners are hitting the first decade of fixture failures and kid-related drywall damage. We help prioritize what matters for resale vs. daily living.",
        "scheduling": "Dispatch runs from 1225 7th St S, Safety Harbor 34695. Land O' Lakes jobs get a written estimate after photos or a quick site look — book online or call (813) 649-3341 when water is active.",
        "scope_note": 'Handyman scope only: we swap fixtures on existing rough-in, patch drywall, adjust doors, and finish paint-ready — no repipes, panel upgrades, or permit-level GC work.',
        "closing": "Explore our {county_link}, browse the Land O' Lakes job list above, and see matching work in our project gallery. Leaks and safety issues — call, do not wait on email.",
        "faq_price": ("How much does handyman estimate pinellas county cost in Land O' Lakes?", "Pricing depends on access, parts, and finish work. Defined Land O' Lakes scopes can be flat-rate after photos; open punch lists may be hourly with our published minimum visit."),
        "faq_licensed": ("Can a handyman do plumbing or electrical work in Land O' Lakes?", "Knight Group performs handyman-scope fixture swaps and like-for-like replacements in Land O' Lakes. Work requiring a licensed plumber, electrician, or permit is referred before tools come out."),
        "faq_schedule": ("How fast can you reach Land O' Lakes for handyman land o lakes fl?", "Most Land O' Lakes requests schedule within one to two business days on existing Pasco County routes. Active leaks get priority when you call (813) 649-3341 directly."),
    },
}

COUNTY_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "pinellas": {
        "hero_lead": 'Pinellas County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'handyman pinellas county and handyman company pinellas: drywall, fixture plumbing, doors. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers Pinellas County on daily routes from Safety Harbor — search handyman pinellas county and you get a local insured crew, not a referral marketplace. We handle fixture plumbing, drywall, carpentry, painting touch-ups, and doors within handyman scope.',
        "scheduling": 'Book Pinellas County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Pinellas County. Licensed trades are referred when permits, repipes, or panel work are required.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Pinellas County proof. Emergency leaks — call first.',
    },
    "hillsborough": {
        "hero_lead": 'Hillsborough County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'handyman near me small jobs and handyman tampa bay: drywall, fixture plumbing, doors. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers Hillsborough County on daily routes from Safety Harbor — search handyman near me small jobs and you get a local insured crew, not a referral marketplace. We handle fixture plumbing, drywall, carpentry, painting touch-ups, and doors within handyman scope.',
        "scheduling": 'Book Hillsborough County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Hillsborough County. Licensed trades are referred when permits, repipes, or panel work are required.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Hillsborough County proof. Emergency leaks — call first.',
    },
    "pasco": {
        "hero_lead": 'Pasco County handyman routes from Safety Harbor — fixture work, drywall, doors, and punch-list repairs with written estimates.',
        "meta_description": 'plumbing services in pinellas county and handyman pasco county fl: drywall, fixture plumbing, doors. Registered and insured. Free estimate.',
        "opening": 'Knight Group covers Pasco County on daily routes from Safety Harbor — search plumbing services in pinellas county and you get a local insured crew, not a referral marketplace. We handle fixture plumbing, drywall, carpentry, painting touch-ups, and doors within handyman scope.',
        "scheduling": 'Book Pasco County work with photos online or call (813) 649-3341. We confirm your city fits the current route before locking an arrival window.',
        "scope_note": 'Handyman-scope repairs only across Pasco County. Licensed trades are referred when permits, repipes, or panel work are required.',
        "closing": 'Tour city pages below, compare pricing, and view our gallery for Pasco County proof. Emergency leaks — call first.',
    },
}

COMBO_PAGE_COPY: dict[str, dict[str, str | tuple[str, str]]] = {
    "clearwater-sink-repair": {
        "hero_lead": 'Sink And Faucet Repair in Clearwater — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'sink repair clearwater in Clearwater: handyman-scope sink and faucet repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for sink repair clearwater in Clearwater should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Clearwater from Safety Harbor with documented scope and plumbing repair clearwater fl experience on real homes.',
        "follow_through": 'After the primary sink and faucet repair task, we sequence drywall, caulk, or paint so Clearwater homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Clearwater sink and faucet repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "clearwater-drywall-repair": {
        "hero_lead": 'Drywall Repair in Clearwater — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'plumbing repair clearwater fl in Clearwater: handyman-scope drywall repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for plumbing repair clearwater fl in Clearwater should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Clearwater from Safety Harbor with documented scope and drywall repair clearwater fl experience on real homes.',
        "follow_through": 'After the primary drywall repair task, we sequence drywall, caulk, or paint so Clearwater homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Clearwater drywall repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "safety-harbor-home-repair": {
        "hero_lead": 'Home Repair in Safety Harbor — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'general home repairs pinellas in Safety Harbor: handyman-scope home repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for general home repairs pinellas in Safety Harbor should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Safety Harbor from Safety Harbor with documented scope and knight group handyman experience on real homes.',
        "follow_through": 'After the primary home repair task, we sequence drywall, caulk, or paint so Safety Harbor homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Safety Harbor home repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "palm-harbor-drywall-repair": {
        "hero_lead": 'Drywall Repair in Palm Harbor — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'handyman pinellas county in Palm Harbor: handyman-scope drywall repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for handyman pinellas county in Palm Harbor should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Palm Harbor from Safety Harbor with documented scope and drywall repair palm harbor experience on real homes.',
        "follow_through": 'After the primary drywall repair task, we sequence drywall, caulk, or paint so Palm Harbor homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Palm Harbor drywall repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "largo-toilet-repair": {
        "hero_lead": 'Toilet Repair in Largo — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'plumbing services in pinellas county in Largo: handyman-scope toilet repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for plumbing services in pinellas county in Largo should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Largo from Safety Harbor with documented scope and toilet repair largo fl experience on real homes.',
        "follow_through": 'After the primary toilet repair task, we sequence drywall, caulk, or paint so Largo homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Largo toilet repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "oldsmar-door-adjustment": {
        "hero_lead": 'Door Adjustment in Oldsmar — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'door repair pinellas county in Oldsmar: handyman-scope door adjustment. Registered and insured. Free written estimate.',
        "opening": 'Searches for door repair pinellas county in Oldsmar should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Oldsmar from Safety Harbor with documented scope and sliding door repair pinellas experience on real homes.',
        "follow_through": 'After the primary door adjustment task, we sequence drywall, caulk, or paint so Oldsmar homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Oldsmar door adjustment with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "dunedin-trim-repair": {
        "hero_lead": 'Trim Repair in Dunedin — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'carpenter pinellas county in Dunedin: handyman-scope trim repair. Registered and insured. Free written estimate.',
        "opening": 'Searches for carpenter pinellas county in Dunedin should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Dunedin from Safety Harbor with documented scope and trim repair dunedin experience on real homes.',
        "follow_through": 'After the primary trim repair task, we sequence drywall, caulk, or paint so Dunedin homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Dunedin trim repair with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
    "seminole-interior-painting": {
        "hero_lead": 'Interior Painting in Seminole — local Serper-targeted help, written estimates, paint-ready finish work.',
        "meta_description": 'handyman painting pinellas county in Seminole: handyman-scope interior painting. Registered and insured. Free written estimate.',
        "opening": 'Searches for handyman painting pinellas county in Seminole should land on a crew that knows local housing — not a generic statewide ad. Knight Group serves Seminole from Safety Harbor with documented scope and interior painting seminole fl experience on real homes.',
        "follow_through": 'After the primary interior painting task, we sequence drywall, caulk, or paint so Seminole homeowners are not hiring a second vendor for finish work.',
        "booking": 'Book Seminole interior painting with photos, call (813) 649-3341 for active leaks, or view the city handyman page for broader repair lists.',
    },
}


def city_copy(slug: str) -> dict:
    return dict(CITY_PAGE_COPY.get(slug, {}))


def county_copy(slug: str) -> dict:
    return dict(COUNTY_PAGE_COPY.get(slug, {}))


def combo_copy(slug: str) -> dict:
    return dict(COMBO_PAGE_COPY.get(slug, {}))
