"""Unique local context for city, county, and city-service geo pages."""

from __future__ import annotations

# gallery_category maps to gallery_pool SERVICE_PARENT_TO_CATEGORY values where useful
CITY_PROFILES: dict[str, dict] = {
    "safety-harbor": {
        "housing": "Downtown Safety Harbor blends 1920s bungalows and brick streets with newer townhomes near the marina. Many properties still have original cast-iron drains, wood siding, and single-pane Florida rooms that need careful handyman upkeep.",
        "areas": "downtown, Philippe Park corridor, Garrard Avenue, and Harbor Oaks",
        "climate": "Harbor humidity and afternoon storms stress exterior caulk, soffit vents, and porch ceilings faster than inland subdivisions.",
        "jobs": [
            "Historic-home trim repair and paint touch-ups without disturbing original profiles",
            "Bathroom fixture swaps in older block homes with corroded angle stops",
            "Lanai and Florida-room door adjustments after seasonal swelling",
            "Rental turnovers near the spa district and marina walk-ups",
            "Drywall patches after minor roof or AC pan leaks in attic-adjacent ceilings",
            "Shelving and closet builds in compact downtown footprints",
        ],
        "angle": "Knight Group is headquartered on 7th Street South in Safety Harbor — this is our home base, not a distant dispatch hub. Same-day routing is easiest here, and Vince Knight knows the mix of older downtown stock and newer infill along McMullen-Booth.",
        "gallery_category": "general-repairs",
    },
    "clearwater": {
        "housing": "Clearwater spans Gulf beach condos, Island Estates waterfront homes, and inland block ranches from the 1960s–80s. Coachman and Countryside subdivisions add stucco tract homes with aging sliders and original polybutylene-era plumbing connections.",
        "areas": "Island Estates, Coachman Ridge, Countryside, North Clearwater, and Sand Key-adjacent neighborhoods",
        "climate": "Salt air corrodes lanai hardware and screen frames; beach-adjacent units see faster caulk failure in showers and window returns.",
        "jobs": [
            "Sliding glass door roller and track service on lanais facing the Gulf",
            "Sink and faucet repairs in kitchens with swollen cabinet bottoms",
            "Drywall and texture work after bathroom fan or AC condensate events",
            "Screen door and patio panel mesh replacement after storm season",
            "Interior paint touch-ups for condos preparing for seasonal residents",
            "Rental punch lists along US-19 corridor and beach-access communities",
        ],
        "angle": "Clearwater owners often juggle tenant turnovers near the beach and owner-occupied repairs inland. We batch Countryside and Coachman routes with beach condo stops when access windows align — one crew, one estimate, no franchise call center.",
        "gallery_category": "plumbing",
    },
    "dunedin": {
        "housing": "Dunedin mixes downtown craftsman bungalows, golf-course villas, and Honeymoon Island-adjacent cottages. Many homes have wood floors, front porches, and older single-hung windows that need seasonal adjustment.",
        "areas": "downtown Dunedin, Curlew corridor, Skinner Boulevard, and Ozona",
        "climate": "Gulf breezes help drying but also drive salt onto exterior hardware; porch ceilings and fan boxes see moisture staining.",
        "jobs": [
            "Front porch ceiling patches and fan box corrections",
            "Trim and casing repair in older bungalows with settled foundations",
            "Interior painting for downtown rentals and short-term units",
            "Door adjustments on vintage homes with swollen jambs",
            "Custom shelving in smaller downtown kitchens and pantries",
            "Fixture-level plumbing in baths with original tile surrounds",
        ],
        "angle": "Dunedin’s walkable downtown and tight lot lines mean access and parking matter. We plan material carries and protect historic trim profiles when patching — important for homeowners who value the town’s craftsman character.",
        "gallery_category": "carpentry",
    },
    "palm-harbor": {
        "housing": "Palm Harbor features 1980s–2000s master-planned communities, lakefront homes, and established neighborhoods east of US-19. Many properties have two-story layouts, tray ceilings, and original builder-grade fixtures nearing end of life.",
        "areas": "East Lake, Highland Lakes, Crescent Oaks, and downtown Palm Harbor",
        "climate": "Lake humidity and afternoon thunderstorms push water into window returns and garage-to-house transitions if caulk is neglected.",
        "jobs": [
            "Drywall repair after second-floor bath leaks into downstairs ceilings",
            "Toilet and faucet fixture work in aging master baths",
            "Interior paint touch-ups with knockdown texture blending",
            "Garage storage shelving and laundry room organization builds",
            "Door hardware upgrades without changing door slabs",
            "Caulk refresh at tubs, showers, and exterior stucco penetrations",
        ],
        "angle": "East Lake and Highland Lakes homeowners often call for one bathroom issue and discover a short punch list while we are on site. We document each item and quote before expanding scope — common in larger Palm Harbor homes with multiple wet walls.",
        "gallery_category": "general-repairs",
    },
    "largo": {
        "housing": "Largo combines mid-century ranch homes, condo communities near the bay, and newer townhome infill. Original windows, aging HVAC closets, and Florida rooms appear throughout the city’s interior neighborhoods.",
        "areas": "Bardmoor, Ridgecrest, Southwest Largo, and Ulmerton corridor",
        "climate": "Flat lots and mature trees mean clogged gutters overflow into fascia and soffits — we often patch drywall after those minor water paths.",
        "jobs": [
            "Toilet repairs and wax ring corrections in single-bath ranches",
            "Drywall patches in Florida rooms and enclosed patios",
            "Blind and hardware installs for condo turnovers",
            "Interior door adjustments after humidity cycles",
            "Water-damage drywall closeout after minor roof or AC events",
            "Kitchen faucet and disposal swaps on original cabinetry",
        ],
        "angle": "Largo’s central Pinellas location makes it a natural mid-route stop between Safety Harbor and the beaches. We schedule Bardmoor and Ridgecrest blocks together to keep drive time low and arrival windows tight.",
        "gallery_category": "plumbing",
    },
    "oldsmar": {
        "housing": "Oldsmar bridges Tampa Bay suburbs and Pinellas — mix of 1970s ranches, waterfront properties along Old Tampa Bay, and newer townhomes near State Road 580. Many kitchens and baths retain original layouts with tight clearances.",
        "areas": "East Lake Woodlands edge, State Road 580 corridor, and waterfront streets off Shore Drive",
        "climate": "Bayfront properties see wind-driven rain at door thresholds; inland homes face standard Florida humidity in slab-on-grade baths.",
        "jobs": [
            "Door adjustments on exterior entries after threshold settling",
            "Kitchen and bath fixture repairs in compact galley layouts",
            "Drywall repair after window leak staining on bay-facing rooms",
            "Screen and sliding door service on lanais",
            "Paint touch-ups for move-in-ready rentals",
            "Shutoff valve replacements before larger plumbing events",
        ],
        "angle": "Oldsmar sits on our daily route between Hillsborough jobs and central Pinellas. Homeowners here benefit from a team that already crosses the bay — not a contractor who treats Oldsmar as out of territory.",
        "gallery_category": "doors-windows",
    },
    "tarpon-springs": {
        "housing": "Tarpon Springs includes sponge-dock era homes, Greek community neighborhoods near the Anclote River, and newer subdivisions north along Keystone Road. Older block construction and stucco overlays are common near the historic district.",
        "areas": "historic district, Keystone Road corridor, East Lake Tarpon area, and Gulf-adjacent streets",
        "climate": "River humidity and older plumbing stacks create more frequent fixture and drain access issues in vintage homes.",
        "jobs": [
            "Fixture repairs in older baths with tiled walls and tight access",
            "Exterior wood trim and fascia patches before painting season",
            "Interior drywall repair in homes with plaster-over-block finishes",
            "Door and window hardware alignment on older single-hung units",
            "Rental turnovers near the sponge docks and downtown rentals",
            "Caulking at stucco penetrations and hose bib surrounds",
        ],
        "angle": "Tarpon Springs’ older housing stock rewards technicians who understand tight wet walls and fragile tile. Vince Knight’s plumbing background helps diagnose whether a leak stays handyman scope or needs a licensed repipe referral.",
        "gallery_category": "plumbing",
    },
    "seminole": {
        "housing": "Seminole features 1960s–80s ranch homes, bay-adjacent properties near Boca Ciega Bay, and condo communities along Park Boulevard. Many interiors still have popcorn ceilings, original oak cabinets, and aging sliding doors.",
        "areas": "Park Boulevard corridor, Orange Grove, Bay Pines adjacency, and Seminole Lake neighborhoods",
        "climate": "Bay moisture drives interior paint failure on exterior walls and lanai transitions; popcorn ceiling stains follow minor roof events.",
        "jobs": [
            "Interior painting and ceiling touch-ups after stain blocking",
            "Sliding door and screen repairs on lanais facing the bay",
            "Drywall patches with texture blending on popcorn-adjacent repairs",
            "Kitchen cabinet hinge and alignment fixes without full remodel",
            "Fixture swaps in baths with limited shutoff access",
            "Punch-list work for condo associations and individual unit owners",
        ],
        "angle": "Seminole homeowners along Park Boulevard often need paint-ready drywall repair after humidity stains — we sequence primer, texture, and topcoat so patches do not flash under afternoon sun.",
        "gallery_category": "painting",
    },
    "st-petersburg": {
        "housing": "St. Petersburg spans historic Kenwood bungalows, downtown high-rises, Shore Acres flood-zone cottages, and mid-century homes in Greater Pinellas Point. Housing age and elevation vary block by block.",
        "areas": "Kenwood, Old Northeast, Shore Acres, Greater Pinellas Point, and western St. Pete near Tyrone",
        "climate": "Tropical storms test soffits, fascia, and window caulking; older pier-and-beam pockets need careful moisture diagnosis before drywall closeout.",
        "jobs": [
            "Historic trim repair with paint-grade finishing in Kenwood and Old Northeast",
            "Drywall and water-damage repair after storm-driven leaks",
            "Fixture-level plumbing in bungalows with raised foundations",
            "Interior paint touch-ups for downtown condos and rentals",
            "Door and hardware work on vintage single-panel doors",
            "Post-insurance minor repairs that do not require a GC license",
        ],
        "angle": "St. Pete’s neighborhood variety means we confirm access, parking, and scope before dispatch — a Kenwood bungalow repair differs from a Tyrone condo turnover. Photos through our booking form speed that conversation.",
        "gallery_category": "general-repairs",
    },
    "tampa": {
        "housing": "Tampa includes Hyde Park bungalows, South Tampa block homes, Westshore condos, and Carrollwood-era ranches. Hillsborough’s largest city mixes historic wood frame, stucco subdivisions, and newer townhome infill.",
        "areas": "Hyde Park, South Tampa, Westshore, New Tampa edges, and MacDill-adjacent neighborhoods",
        "climate": "Summer thunderstorms and afternoon heat cycles swell doors and stress attic-adjacent drywall when AC condensate pans overflow.",
        "jobs": [
            "Drywall ceiling repair after AC attic leaks in single-story ranches",
            "Bathroom fixture and toilet work in South Tampa remodel-ready homes",
            "Interior paint touch-ups for rentals between tenant turns",
            "Door adjustments on older bungalows with settled pier foundations",
            "Kitchen faucet and disposal replacements in original layouts",
            "Shelving and storage builds in garages and laundry rooms",
        ],
        "angle": "We route Tampa from Safety Harbor across the bay — prioritizing South Tampa and Westshore clusters on planned days rather than random cross-county zigzags. That keeps estimates honest and arrival windows realistic.",
        "gallery_category": "general-repairs",
    },
    "town-n-country": {
        "housing": "Town 'n' Country is largely 1970s–90s suburban ranches and villa communities west of Tampa. Original windows, aluminum sliders, and builder-grade baths are common throughout the area.",
        "areas": "Countryway, Westchase border streets, Memorial Highway corridor, and Hillsborough Avenue neighborhoods",
        "climate": "Inland humidity without bay breeze means bath exhaust and caulking failures show up as ceiling stains and peeling paint faster.",
        "jobs": [
            "Sliding door and window screen repairs on original aluminum units",
            "Toilet and faucet fixture corrections in aging master baths",
            "Drywall patches in vaulted-ceiling living rooms after roof events",
            "Interior paint for villa communities between owners",
            "Garage storage and shelving for single-car garage layouts",
            "Door adjustments on patio entries that bind in summer",
        ],
        "angle": "Town 'n' Country’s villa HOAs often need discrete, insured vendors for interior repairs — we provide written scope and respect community parking rules on every visit.",
        "gallery_category": "doors-windows",
    },
    "westchase": {
        "housing": "Westchase is a master-planned community with uniform stucco exteriors, two-story homes, and community standards for exterior appearance. Interiors often have open plans with tall ceilings and builder-grade lighting.",
        "areas": "Westchase proper, Glen Laurel, and adjacent townhome pockets",
        "climate": "Community drainage and irrigation keep lots green but also push moisture against foundation stucco — caulk lines at walks and patios need periodic refresh.",
        "jobs": [
            "Interior paint touch-ups with careful masking in open floor plans",
            "Drywall repair after furniture impacts and stairwell scuffs",
            "Light fixture swaps on existing boxes within handyman electrical scope",
            "Trim repair and caulk lines before HOA photo compliance",
            "Closet and pantry shelving tailored to standard Westchase layouts",
            "Bathroom fixture updates without changing wet-wall locations",
        ],
        "angle": "Westchase homeowners expect neat work and clean job sites — standard for us. We protect floors, label removed hardware, and leave HOA-visible areas broom-clean before leaving the community gates.",
        "gallery_category": "painting",
    },
    "citrus-park": {
        "housing": "Citrus Park combines retail-corridor suburbs with established ranches near Gunn Highway and newer townhomes by the mall district. Many homes have enclosed lanais converted to living space.",
        "areas": "Gunn Highway neighborhoods, Citrus Park Town Center adjacency, and Carrollwood border streets",
        "climate": "Enclosed lanai conversions often hide slow leaks at slab penetrations — we patch drywall only after the moisture source is stable.",
        "jobs": [
            "Drywall repair on former lanai walls and ceiling transitions",
            "Plumbing fixture work in kitchens opened to family rooms",
            "Interior door adjustments where slab homes have settled",
            "Paint touch-ups on accent walls and tray ceilings",
            "TV mounts and shelving on open-plan walls with blocking checks",
            "Rental turnovers near the university and hospital corridors",
        ],
        "angle": "Citrus Park’s mix of owner-occupied and rental stock near major employers means fast scheduling matters. We confirm whether your job is handyman scope before rolling through Gunn Highway traffic.",
        "gallery_category": "general-repairs",
    },
    "carrollwood": {
        "housing": "Carrollwood features 1970s–80s ranches, Carrollwood Village planned sections, and lakefront homes on Carrollwood Country Club waterways. Original shingle roofs and aging baths are frequent upgrade triggers.",
        "areas": "Carrollwood Village, Carrollwood Country Club, and Northdale border neighborhoods",
        "climate": "Lake-adjacent homes see higher humidity at window returns; inland sections face standard Florida door swelling in summer.",
        "jobs": [
            "Bathroom fixture and toilet repairs in original hall-bath layouts",
            "Drywall repair after ceiling stains from bathroom exhaust issues",
            "Interior painting with knockdown texture matching",
            "Door and trim work on lakefront entries with expanded glazing",
            "Kitchen updates limited to hardware, faucets, and backsplash caulk",
            "Punch-list repairs for sellers preparing Carrollwood listings",
        ],
        "angle": "Carrollwood sellers often need a short punch list before photos — we quote flat-rate when the scope is defined and can bundle paint, drywall, and fixture items in one visit.",
        "gallery_category": "general-repairs",
    },
    "northdale": {
        "housing": "Northdale is a suburban pocket of 1980s ranches and two-story homes between Carrollwood and Citrus Park. Many properties retain original brass fixtures, oak cabinets, and textured ceilings.",
        "areas": "Northdale Golf Club neighborhoods, Northdale Boulevard corridor, and Hamilton Run",
        "climate": "Mature oak canopy shades homes but also holds humidity against soffits — minor fascia and soffit repairs often pair with interior ceiling patches.",
        "jobs": [
            "Texture matching on ceiling repairs near canned lights",
            "Fixture swaps updating brass to brushed nickel on existing rough-in",
            "Drywall patches in kids’ rooms and hallways from daily wear",
            "Interior door planing when humidity binds closet and bath doors",
            "Laundry room shelving and faucet replacements",
            "Caulk refresh at tubs and showers in original hall baths",
        ],
        "angle": "Northdale homeowners often modernize one room at a time — faucet and hardware updates plus paint touch-ups are a natural bundle without opening walls.",
        "gallery_category": "painting",
    },
    "egypt-lake-leto": {
        "housing": "Egypt Lake-Leto has dense mid-century ranches, duplex rentals, and modest block homes near busy corridors. Many properties serve as workforce housing with high turnover wear.",
        "areas": "Egypt Lake, Leto High School corridor, and Waters Avenue neighborhoods",
        "climate": "High tenant turnover accelerates door, lock, and drywall damage — repairs must be durable and fast to minimize vacancy days.",
        "jobs": [
            "Rental turnovers: locks, blinds, patch-and-paint, and fixture checks",
            "Hole-in-wall repairs between tenants in duplex units",
            "Toilet and faucet repairs in compact baths",
            "Interior door replacements on existing hinges where slabs are damaged",
            "Garbage disposal swaps in older kitchens",
            "Emergency leak stabilization within handyman plumbing scope",
        ],
        "angle": "Landlords in Egypt Lake-Leto need reliable turnaround times. We batch multi-unit lists when keys align and provide itemized written estimates for owner approval.",
        "gallery_category": "plumbing",
    },
    "temple-terrace": {
        "housing": "Temple Terrace includes river-adjacent homes near the Hillsborough River, mid-century neighborhoods by USF, and tree-canopied streets with ranch and split-level layouts.",
        "areas": "Temple Terrace Estates, river roads, and USF-adjacent rentals",
        "climate": "River humidity and large oaks mean exterior wood trim and porch columns need more frequent spot repair than inland Tampa suburbs.",
        "jobs": [
            "Porch column and trim repairs with paint-ready finishing",
            "Drywall patches in split-level homes with stairwell scuffs",
            "Fixture repairs in rental units near the university",
            "Interior painting for student rental turnovers between semesters",
            "Door adjustments on river-facing entries with moisture swell",
            "Shelving and desk builds in home offices carved from spare rooms",
        ],
        "angle": "Temple Terrace’s river neighborhoods reward technicians who understand exterior wood repair sequencing — prime, caulk, then paint — so repairs survive the next wet season.",
        "gallery_category": "carpentry",
    },
    "holiday": {
        "housing": "Holiday features 1960s–70s ranch homes, canal-front properties, and retiree communities along US-19. Many homes sit on slabs with enclosed lanais and aging copper or galvanized supply lines at fixtures.",
        "areas": "Holiday Lake, Forest Hills, Aloha Gardens, and US-19 corridor",
        "climate": "Canal-front humidity and older plumbing at fixtures mean more shutoff and supply-line replacements than newer Pasco subdivisions.",
        "jobs": [
            "Fixture-level plumbing and shutoff replacements in older baths",
            "Drywall repair on enclosed lanai conversions",
            "Screen and sliding door service on canal-facing lanais",
            "Interior paint for seasonal resident move-ins",
            "Mobile-home-adjacent skirting and step repairs where applicable",
            "Grab bar installs when blocking is accessible in retiree baths",
        ],
        "angle": "Holiday’s retiree homeowners often want one trusted vendor for a short list — we explain each repair in plain language and leave written notes when family members manage the property remotely.",
        "gallery_category": "plumbing",
    },
    "trinity": {
        "housing": "Trinity is a newer master-planned area with 1990s–2010s stucco homes, golf communities, and standard builder layouts. Homes are generally in good structural shape but entering fixture and finish wear years.",
        "areas": "Trinity Oaks, Champions Club, and Odessa-border subdivisions",
        "climate": "Newer construction still faces Florida humidity at bath exhausts and exterior door seals — preventive caulk saves drywall patches later.",
        "jobs": [
            "Master bath faucet and toilet updates without layout changes",
            "Interior paint touch-ups after furniture moves and kid damage",
            "Drywall repair from doorknob impacts in two-story stair halls",
            "Closet organization and garage shelving installs",
            "Light fixture swaps on existing connections",
            "Pre-listing punch lists in Trinity resale market",
        ],
        "angle": "Trinity owners often call for one visible repair — a stair hall dent or master bath drip — and add items once trust is established. Written line-item quotes keep that expansion orderly.",
        "gallery_category": "general-repairs",
    },
    "new-port-richey": {
        "housing": "New Port Richey mixes downtown historic homes along the Pithlachascotee River, 1970s ranches, and Gulf-adjacent communities west of US-19. Older downtown stock has wood frame and pier foundations in places.",
        "areas": "downtown NPR, Gulf Harbors edge, Regency Park, and Little Road corridor",
        "climate": "River and Gulf proximity accelerate exterior paint failure and dock-adjacent humidity in lower-level rooms.",
        "jobs": [
            "Historic downtown trim and porch repairs with paint-ready finishes",
            "Drywall repair after window and roof leak staining",
            "Fixture plumbing in older baths with tile surrounds",
            "Interior painting for downtown rentals and winter residents",
            "Screen enclosure and lanai door adjustments",
            "Water-damage closeout after minor flooding events in low-lying blocks",
        ],
        "angle": "New Port Richey’s downtown river homes need careful moisture diagnosis before cosmetic patches — we stabilize leaks first, then texture and paint so stains do not return next storm season.",
        "gallery_category": "general-repairs",
    },
    "elfers": {
        "housing": "Elfers is a compact Pasco community with modest ranches, mobile homes, and older block construction west of New Port Richey. Properties are often value-focused with practical repair needs.",
        "areas": "Elfers Parkway corridor, Beaver Lake adjacency, and Little Road side streets",
        "climate": "Older roof and window details on smaller homes mean more interior stain repairs than new construction elsewhere in Pasco.",
        "jobs": [
            "Affordable drywall patch-and-paint for rentals and owner-occupants",
            "Toilet and faucet repairs on aging fixtures",
            "Door adjustments and lock replacements for turnovers",
            "Mobile home skirting, steps, and moisture barrier touch-ups",
            "Kitchen disposal and faucet swaps",
            "Caulk refresh at tubs and exterior penetrations",
        ],
        "angle": "Elfers homeowners want straightforward pricing without minimum-job games — we quote defined scopes flat-rate when photos show the full problem.",
        "gallery_category": "general-repairs",
    },
    "seven-springs": {
        "housing": "Seven Springs is a wooded Pasco area with 1980s–90s homes on larger lots, some near the Suncoast Parkway. Properties often have well and septic considerations at outbuildings and guest baths.",
        "areas": "Seven Springs Boulevard, Parkway access neighborhoods, and wooded subdivisions",
        "climate": "Tree cover holds humidity against wood siding and fascia; interior mold staining follows bath vents that terminate into attics incorrectly.",
        "jobs": [
            "Drywall repair after bath fan moisture stains in attic-adjacent ceilings",
            "Exterior wood trim patches on shaded elevations",
            "Interior paint in open living areas with cathedral ceilings",
            "Fixture repairs in guest baths and pool baths",
            "Shelving in garages and workshops on larger lots",
            "Door service on patio entries facing wooded yards",
        ],
        "angle": "Seven Springs’ larger lots mean we confirm tool access and power availability for exterior wood repair — a quick phone call saves a wasted trip down wooded driveways.",
        "gallery_category": "carpentry",
    },
    "jasmine-estates": {
        "housing": "Jasmine Estates is a dense 1960s–70s subdivision with slab ranches, carports, and many long-term rentals. Original kitchens and baths are compact and often unrenovated.",
        "areas": "Jasmine Boulevard, US-19 adjacency, and interior loop streets",
        "climate": "High-density housing and aging roofs produce steady interior stain repair work after minor leaks.",
        "jobs": [
            "Rental turnovers with patch, paint, and fixture checks",
            "Hole-in-wall and ceiling stain blocking before paint",
            "Faucet and toilet repairs in original hall baths",
            "Interior door and hardware replacements",
            "Screen door and window repairs on carport entries",
            "Blind and hardware installs for absentee landlords",
        ],
        "angle": "Jasmine Estates landlords appreciate itemized invoices — we list each room and task so property managers can allocate costs across units.",
        "gallery_category": "painting",
    },
    "beacon-square": {
        "housing": "Beacon Square is a modest Pasco neighborhood of mid-century ranches and duplex rentals near Holiday and New Port Richey. Many homes retain original windows and carport conversions.",
        "areas": "Beacon Square Drive loops and US-19 frontage streets",
        "climate": "Carport conversions and older windows are common leak paths into interior drywall — we repair finishes only after source correction.",
        "jobs": [
            "Drywall patches on carport-adjacent walls",
            "Fixture repairs in compact kitchens and baths",
            "Paint touch-ups for move-in-ready units",
            "Door adjustments on carport entries",
            "Shutoff valve replacements at failing angle stops",
            "Light fixture swaps where boxes are already rated and accessible",
        ],
        "angle": "Beacon Square repairs are often budget-sensitive — we separate must-fix items from cosmetic upgrades so owners can phase work.",
        "gallery_category": "general-repairs",
    },
    "port-richey": {
        "housing": "Port Richey includes riverfront downtown properties, fishing-village era homes, and inland ranches. Gulf access communities west of US-19 see salt air on exterior metals and screens.",
        "areas": "downtown Port Richey, riverfront, and Gulf Harbor-adjacent streets",
        "climate": "Salt air corrodes screen frames and lanai door rollers faster than inland Pasco — preventive adjustment saves full replacements.",
        "jobs": [
            "Sliding door and screen repairs on Gulf-facing lanais",
            "Riverfront porch and soffit patch work",
            "Interior drywall repair after window leaks",
            "Fixture plumbing in older downtown baths",
            "Paint touch-ups for seasonal residents",
            "Rental turnovers near the marina district",
        ],
        "angle": "Port Richey’s river and Gulf edges mean we carry corrosion-resistant hardware options when replacing rollers and screen corners — small detail that extends the repair.",
        "gallery_category": "doors-windows",
    },
    "land-o-lakes": {
        "housing": "Land O' Lakes blends rapid 2000s–2010s growth subdivisions, Connerton, and older ranches along US-41. Newer homes enter their first fixture and interior wear cycle; older sections need classic Florida ranch repairs.",
        "areas": "Connerton, Oakstead, Land O' Lakes Boulevard corridor, and Suncoast Parkway suburbs",
        "climate": "Newer stucco homes still need bath caulk maintenance; older ranches along US-41 show AC condensate and roof leak stains in ceilings.",
        "jobs": [
            "New-construction warranty-expired punch lists — hardware, caulk, paint",
            "Drywall repair in two-story foyer and stair walls",
            "Master bath fixture updates in Oakstead and Connerton layouts",
            "Garage storage systems on deep garage bays",
            "Interior painting for resale in growing subdivisions",
            "Door adjustments on patio sliders in first-generation wear years",
        ],
        "angle": "Land O' Lakes grew fast — many owners are hitting the first decade of fixture failures and kid-related drywall damage. We help prioritize what matters for resale vs. daily living.",
        "gallery_category": "general-repairs",
    },
}

COUNTY_PROFILES: dict[str, dict] = {
    "pinellas": {
        "hub_name": "Pinellas County",
        "character": "Pinellas is a peninsula county — Gulf beaches on one side, Tampa Bay on the other, and a dense mix of block ranches, mid-rise condos, and historic bungalows in between.",
        "routing": "Knight Group runs Pinellas routes daily from Safety Harbor headquarters. Clearwater, Dunedin, Largo, Palm Harbor, and St. Petersburg are regular stops — not occasional overflow trips.",
        "themes": [
            "Salt air and humidity drive lanai door, screen, and exterior caulk work",
            "Older block homes need fixture-level plumbing without opening walls",
            "Condo and rental turnovers along beach and corridor communities",
            "Storm-season drywall and soffit touch-ups after minor water intrusion",
            "Historic trim repair in Safety Harbor, Dunedin, and St. Pete neighborhoods",
        ],
        "gallery_category": "general-repairs",
    },
    "hillsborough": {
        "hub_name": "Hillsborough County",
        "character": "Hillsborough spans Tampa’s urban core, South Tampa bungalows, and northwest suburbs like Carrollwood, Citrus Park, and Westchase — larger lots, more ranches, and bay-crossing commutes for vendors who do not plan routes.",
        "routing": "We batch Hillsborough work on planned bay crossings from Safety Harbor — South Tampa, Westchase, Carrollwood, and Temple Terrace clusters reduce windshield time and keep estimates fair.",
        "themes": [
            "AC condensate and attic leaks into drywall ceilings in slab ranches",
            "Rental turnovers near USF and employer corridors",
            "Master-planned community interior paint and fixture refresh cycles",
            "Door and trim adjustment on 1970s–80s subdivision stock",
            "Pre-listing punch lists in Carrollwood and Citrus Park resale markets",
        ],
        "gallery_category": "general-repairs",
    },
    "pasco": {
        "hub_name": "Pasco County",
        "character": "Pasco stretches from Gulf-adjacent Holiday and Port Richey through inland Trinity and Land O' Lakes growth corridors — older retirees, river towns, and newer master-planned subdivisions on the same service map.",
        "routing": "Pasco routes often chain Holiday, New Port Richey, Trinity, and Land O' Lakes on west-county days — efficient for homeowners who need one vendor across multiple properties.",
        "themes": [
            "Older fixture and shutoff replacements in 1960s–70s ranches",
            "River and Gulf humidity repairs in NPR and Port Richey",
            "New subdivision first-decade wear — sliders, caulk, and stair hall drywall",
            "Landlord turnovers in Jasmine Estates and Egypt Lake-adjacent density",
            "Lanai and screen repairs on canal-front Holiday homes",
        ],
        "gallery_category": "plumbing",
    },
}

COMBO_PROFILES: dict[str, dict] = {
    "clearwater-sink-repair": {
        "service_label": "sink and faucet repair",
        "niche_slug": "sink-faucet-repair",
        "focus": "Clearwater kitchens and baths — especially Coachman and beach condos — see supply-line leaks, corroded angle stops, and swollen cabinet bottoms under sinks.",
        "jobs": [
            "Leak diagnosis under kitchen and bath sinks before cabinet damage spreads",
            "Faucet cartridge and sprayer hose replacements on original rough-in",
            "P-trap reseats and drain basket corrections",
            "Shutoff replacements when valves will not fully close",
            "Drywall and cabinet bottom drying coordination after leak stabilization",
        ],
    },
    "clearwater-drywall-repair": {
        "service_label": "drywall repair",
        "niche_slug": "drywall-repair",
        "focus": "Clearwater homes patch ceiling stains after AC and roof events, doorknob holes in beach rentals, and texture blending on knockdown and orange-peel finishes.",
        "jobs": [
            "Ceiling stain blocking after minor leaks in Gulf-adjacent units",
            "Hole patches from door impacts in rental turnovers",
            "Texture matching on knockdown living room ceilings",
            "Garage and lanai conversion wall repairs",
            "Paint-ready finishing for listing photos inland and on the beach",
        ],
    },
    "safety-harbor-home-repair": {
        "service_label": "home repair",
        "niche_slug": "home-repair-near-me",
        "focus": "Safety Harbor homeowners mix downtown historic upkeep with modern townhome punch lists — one team for mixed-trade visits from our headquarters city.",
        "jobs": [
            "Multi-room punch lists spanning plumbing fixtures, drywall, and doors",
            "Historic trim and porch repair with paint-grade sequencing",
            "Rental turnovers near downtown and the marina",
            "Post-plumber drywall closeout in older block homes",
            "Shelving and hardware installs in compact footprints",
        ],
    },
    "palm-harbor-drywall-repair": {
        "service_label": "drywall repair",
        "niche_slug": "drywall-repair",
        "focus": "Palm Harbor two-story homes frequently need ceiling patches under master baths and stair hall scuffs in East Lake and Highland Lakes communities.",
        "jobs": [
            "Second-floor bath leak patches in downstairs ceilings",
            "Knockdown texture blending on tray ceilings",
            "Doorknob and furniture impact repairs in hallways",
            "Garage-to-house wall patches after vehicle bumps",
            "Stain blocking before topcoat in humidity-stressed rooms",
        ],
    },
    "largo-toilet-repair": {
        "service_label": "toilet repair",
        "niche_slug": "toilet-repair",
        "focus": "Largo ranches and condos often run original toilets past their reliable years — flappers, fill valves, wax rings, and supply leaks at the base.",
        "jobs": [
            "Running toilet diagnostics and internal component replacements",
            "Wax ring corrections when floors show soft spots or odors",
            "Supply line and shutoff replacements at failing connections",
            "Seat, handle, and flush mechanism upgrades on existing bowls",
            "Coordination with drywall repair if prior leaks stained adjacent rooms",
        ],
    },
    "oldsmar-door-adjustment": {
        "service_label": "door adjustment",
        "niche_slug": "door-adjustment",
        "focus": "Oldsmar entries and lanais bind after humidity cycles and threshold settling — especially bay-facing exterior doors and patio sliders.",
        "jobs": [
            "Hinge shim and screw reinforcement on dragging entries",
            "Latch alignment when strikes no longer catch",
            "Slider height and roller adjustments on lanais",
            "Weatherstrip and sweep replacements at exterior doors",
            "Interior door planing when slab homes swell in summer",
        ],
    },
    "dunedin-trim-repair": {
        "service_label": "trim repair",
        "niche_slug": "trim-repair",
        "focus": "Dunedin bungalows and porches need baseboard, casing, and shoe molding repairs that respect older profiles before paint.",
        "jobs": [
            "Scarf-joint baseboard replacements in high-traffic halls",
            "Door casing repair after pet or furniture damage",
            "Porch column and rail trim patches with exterior-grade prep",
            "Shoe molding gaps after seasonal humidity swings",
            "Caulk and fill before paint on historic profiles",
        ],
    },
    "seminole-interior-painting": {
        "service_label": "interior painting",
        "niche_slug": "interior-painting",
        "focus": "Seminole homes — especially bay-adjacent and Park Boulevard corridors — need stain blocking, popcorn-adjacent ceiling touch-ups, and room refreshes.",
        "jobs": [
            "Stain blocking on exterior-facing walls after humidity damage",
            "Ceiling touch-ups near bath exhaust failures",
            "Accent wall and room repaints with clean cut lines",
            "Trim and baseboard enamel after carpentry repairs",
            "Rental turnovers with neutral palette resets",
        ],
    },
}
