#!/usr/bin/env python3
"""Page content definitions for SEO expansion."""

from __future__ import annotations

SCOPE_DISCLAIMER = """
<div class="kg-scope-disclaimer">
  <p><strong>Handyman scope notice:</strong> Knight Group provides handyman-scope fixture replacement, minor repairs, and troubleshooting using existing connections. We do not perform work requiring a licensed plumbing, electrical, HVAC, or general contractor license. If a job requires a permit or licensed trade contractor, we identify that before work begins and refer or coordinate appropriately.</p>
</div>
"""

COUNTY_REGIONS = [
    {
        "id": "pinellas",
        "hub_slug": "pinellas",
        "hub_name": "Pinellas County",
        "nav_label": "Pinellas County Handyman Services",
        "overview_label": "All Pinellas County",
        "cities": [
            {"slug": "safety-harbor", "name": "Safety Harbor", "seo_primary": True},
            {"slug": "clearwater", "name": "Clearwater", "seo_primary": True},
            {"slug": "dunedin", "name": "Dunedin", "seo_primary": True},
            {"slug": "palm-harbor", "name": "Palm Harbor", "seo_primary": True},
            {"slug": "largo", "name": "Largo", "seo_primary": True},
            {"slug": "oldsmar", "name": "Oldsmar", "seo_primary": True},
            {"slug": "tarpon-springs", "name": "Tarpon Springs", "seo_primary": True},
            {"slug": "seminole", "name": "Seminole", "seo_primary": True},
            {"slug": "st-petersburg", "name": "St. Petersburg", "seo_primary": True},
        ],
    },
    {
        "id": "hillsborough",
        "hub_slug": "hillsborough",
        "hub_name": "Hillsborough County",
        "nav_label": "Hillsborough County Handyman Services",
        "overview_label": "All Hillsborough County",
        "cities": [
            {"slug": "tampa", "name": "Tampa", "seo_primary": True},
            {"slug": "town-n-country", "name": "Town 'n' Country", "seo_primary": True},
            {"slug": "westchase", "name": "Westchase", "seo_primary": True},
            {"slug": "citrus-park", "name": "Citrus Park", "seo_primary": True},
            {"slug": "carrollwood", "name": "Carrollwood", "seo_primary": True},
            {"slug": "northdale", "name": "Northdale", "seo_primary": False},
            {"slug": "egypt-lake-leto", "name": "Egypt Lake-Leto", "seo_primary": False},
            {"slug": "temple-terrace", "name": "Temple Terrace", "seo_primary": False},
        ],
    },
    {
        "id": "pasco",
        "hub_slug": "pasco",
        "hub_name": "Pasco County",
        "nav_label": "Pasco County Handyman Services",
        "overview_label": "All Pasco County",
        "cities": [
            {"slug": "holiday", "name": "Holiday", "seo_primary": True},
            {"slug": "trinity", "name": "Trinity", "seo_primary": True},
            {"slug": "new-port-richey", "name": "New Port Richey", "seo_primary": True},
            {"slug": "elfers", "name": "Elfers", "seo_primary": True},
            {"slug": "seven-springs", "name": "Seven Springs", "seo_primary": False},
            {"slug": "jasmine-estates", "name": "Jasmine Estates", "seo_primary": False},
            {"slug": "beacon-square", "name": "Beacon Square", "seo_primary": False},
            {"slug": "port-richey", "name": "Port Richey", "seo_primary": False},
            {"slug": "land-o-lakes", "name": "Land O' Lakes", "seo_primary": True},
        ],
    },
]

# Backward-compatible flat list used by combo pages and legacy imports.
CITIES = [
    (city["slug"], city["name"])
    for region in COUNTY_REGIONS
    for city in region["cities"]
]

NICHE_SERVICES = [
    {
        "slug": "home-repair-near-me",
        "parent": "handyman",
        "title": "Home Repair Near Me in Pinellas County FL | Knight Group",
        "h1": "Home repair near me in Pinellas County",
        "lead": "One local team for drywall, fixtures, doors, punch-list repairs, and mixed trade work across Safety Harbor, Clearwater, and Pinellas County.",
        "queries": ["home repair near me", "knights home repair"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "small-jobs",
        "parent": "handyman",
        "title": "Small Job Handyman in Pinellas County FL | Knight Group",
        "h1": "Small jobs handyman in Pinellas County",
        "lead": "No oversized minimums — book practical small repairs, fixture swaps, and punch-list items with a registered local handyman company.",
        "queries": ["handyman near me small jobs"],
        "hero": "handyman.webp",
        "scope": False,
    },
    {
        "slug": "small-job-carpenter",
        "parent": "carpentry-framing",
        "title": "Small Job Carpenter in Pinellas County FL | Knight Group",
        "h1": "Small job carpenter near me",
        "lead": "Trim, shelving, door frames, and repair carpentry for homeowners who need one dependable local carpenter-handyman.",
        "queries": ["small job carpenter near me", "carpentry services near me"],
        "hero": "carpentry-framing.webp",
        "scope": False,
    },
    {
        "slug": "sink-faucet-repair",
        "parent": "plumbing-services",
        "title": "Sink & Faucet Repair in Clearwater FL | Knight Group",
        "h1": "Sink and faucet repair in Pinellas County",
        "lead": "Leaks under the cabinet, loose faucets, slow drains, and shutoff issues handled with journeyman plumbing experience on the handyman scope.",
        "queries": ["sink repair clearwater", "handyman plumbing prices"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "drywall-repair",
        "parent": "general-repairs",
        "title": "Drywall Repair Near Me in Pinellas County FL | Knight Group",
        "h1": "Drywall repair near me",
        "lead": "Holes, cracks, ceiling patches, and texture blending after leaks or fixture changes across Pinellas County homes.",
        "queries": ["drywall repair near me"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "sliding-door-repair",
        "parent": "doors-windows",
        "title": "Sliding Door Repair in Pinellas County FL | Knight Group",
        "h1": "Sliding door repair",
        "lead": "Sticky tracks, worn rollers, alignment issues, and weather sealing for patio and sliding doors.",
        "queries": ["sliding door repair"],
        "hero": "doors-windows.webp",
        "scope": False,
    },
    {
        "slug": "drywall-paint-repair",
        "parent": "painting-finishing",
        "title": "Drywall and Paint Repair in Pinellas County FL | Knight Group",
        "h1": "Drywall and paint repair",
        "lead": "Patch, texture, prime, and paint so repairs disappear instead of leaving obvious squares on the wall.",
        "queries": ["drywall and paint repair"],
        "hero": "painting-finishing.webp",
        "scope": False,
    },
    {
        "slug": "water-damage-repair",
        "parent": "general-repairs",
        "title": "Water Damage Repair in Pinellas County FL | Knight Group",
        "h1": "Water damage repair",
        "lead": "Drywall, substrate, caulking, and finish corrections after minor leaks, AC pan issues, and bathroom moisture problems.",
        "queries": ["water damage repair handyman"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "screen-door-repair",
        "parent": "doors-windows",
        "title": "Screen Door Repair in Pinellas County FL | Knight Group",
        "h1": "Screen door repair",
        "lead": "Mesh replacement, frame straightening, hardware fixes, and closer adjustments for Florida screen doors.",
        "queries": ["screen door repair"],
        "hero": "doors-windows.webp",
        "scope": False,
    },
    {
        "slug": "trim-repair",
        "parent": "carpentry-framing",
        "title": "Trim Repair in Pinellas County FL | Knight Group",
        "h1": "Trim repair and replacement",
        "lead": "Baseboards, casing, shoe molding, and door trim repairs with paint-ready finishing.",
        "queries": ["trim repair handyman"],
        "hero": "carpentry-framing.webp",
        "scope": False,
    },
    {
        "slug": "faucet-replacement",
        "parent": "plumbing-services",
        "title": "Faucet Replacement in Pinellas County FL | Knight Group",
        "h1": "Faucet replacement",
        "lead": "Kitchen and bath faucet swaps using existing supply lines where connections are sound.",
        "queries": ["faucet replacement handyman"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "toilet-repair",
        "parent": "plumbing-services",
        "title": "Toilet Repair in Pinellas County FL | Knight Group",
        "h1": "Toilet repair and replacement",
        "lead": "Running toilets, weak flushes, leaks at the base, and wax ring corrections within handyman plumbing scope.",
        "queries": ["toilet repair handyman"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "garbage-disposal-replacement",
        "parent": "plumbing-services",
        "title": "Garbage Disposal Replacement | Pinellas County FL",
        "h1": "Garbage disposal replacement",
        "lead": "Swap failed disposals and reconnect drain lines on existing rough-in.",
        "queries": ["garbage disposal replacement"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "shutoff-valve-repair",
        "parent": "plumbing-services",
        "title": "Shutoff Valve Repair in Pinellas County FL | Knight Group",
        "h1": "Shutoff valve repair",
        "lead": "Corroded angle stops and supply valves that will not fully close replaced before bigger leaks happen.",
        "queries": ["shutoff valve replacement"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "drain-unclogging",
        "parent": "plumbing-services",
        "title": "Drain Unclogging Handyman | Pinellas County FL",
        "h1": "Drain unclogging (handyman scope)",
        "lead": "Slow kitchen and bath drains cleared when the issue is accessible without main-line contractor work.",
        "queries": ["drain unclogging handyman"],
        "hero": "plumbing-services.webp",
        "scope": True,
    },
    {
        "slug": "hole-in-wall-repair",
        "parent": "general-repairs",
        "title": "Hole in Wall Repair | Pinellas County FL | Knight Group",
        "h1": "Hole in wall repair",
        "lead": "From doorknob impacts to outlet moves — patch, tape, mud, and texture for paint-ready walls.",
        "queries": ["hole in wall repair"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "caulking-repair",
        "parent": "general-repairs",
        "title": "Caulking Repair in Pinellas County FL | Knight Group",
        "h1": "Caulking repair",
        "lead": "Tub, shower, window, and exterior caulk lines refreshed to stop moisture intrusion in Florida humidity.",
        "queries": ["caulking repair handyman"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "mobile-home-repairs",
        "parent": "general-repairs",
        "title": "Mobile Home Repairs in Pinellas County FL | Knight Group",
        "h1": "Mobile home repairs",
        "lead": "Skirting, subfloor patches, doors, moisture repairs, and punch-list work for mobile and manufactured homes.",
        "queries": ["mobile home repairs pinellas"],
        "hero": "general-repairs.webp",
        "scope": False,
    },
    {
        "slug": "custom-shelving",
        "parent": "carpentry-framing",
        "title": "Custom Shelving in Pinellas County FL | Knight Group",
        "h1": "Custom shelving installation",
        "lead": "Closet rods, laundry shelving, pantry builds, and garage storage tailored to your space.",
        "queries": ["custom shelving handyman"],
        "hero": "carpentry-framing.webp",
        "scope": False,
    },
    {
        "slug": "cabinet-repair",
        "parent": "carpentry-framing",
        "title": "Cabinet Repair in Pinellas County FL | Knight Group",
        "h1": "Cabinet repair",
        "lead": "Hinges, drawer slides, damaged faces, and alignment fixes without a full kitchen remodel.",
        "queries": ["cabinet repair handyman"],
        "hero": "carpentry-framing.webp",
        "scope": False,
    },
    {
        "slug": "door-frame-repair",
        "parent": "carpentry-framing",
        "title": "Door Frame Repair in Pinellas County FL | Knight Group",
        "h1": "Door frame repair",
        "lead": "Strike plates, split jambs, sagging headers, and latch alignment for interior and exterior doors.",
        "queries": ["door frame repair"],
        "hero": "carpentry-framing.webp",
        "scope": False,
    },
    {
        "slug": "door-adjustment",
        "parent": "doors-windows",
        "title": "Door Adjustment in Pinellas County FL | Knight Group",
        "h1": "Door adjustment and hinge repair",
        "lead": "Doors that stick, drag, or will not latch — planed, shimmed, and re-hung in place.",
        "queries": ["door adjustment handyman"],
        "hero": "doors-windows.webp",
        "scope": False,
    },
    {
        "slug": "window-screen-repair",
        "parent": "doors-windows",
        "title": "Window Screen Repair in Pinellas County FL | Knight Group",
        "h1": "Window screen repair",
        "lead": "Screen mesh and frame repairs for windows and porch panels.",
        "queries": ["window screen repair"],
        "hero": "doors-windows.webp",
        "scope": False,
    },
    {
        "slug": "interior-painting",
        "parent": "painting-finishing",
        "title": "Interior Painting Touch-Ups | Pinellas County FL",
        "h1": "Interior painting and touch-ups",
        "lead": "Rooms, accent walls, and repair-area paint with clean cut lines and matched sheen.",
        "queries": ["interior painting handyman"],
        "hero": "painting-finishing.webp",
        "scope": False,
    },
    {
        "slug": "texture-matching",
        "parent": "painting-finishing",
        "title": "Drywall Texture Matching | Pinellas County FL",
        "h1": "Texture matching",
        "lead": "Orange peel, knockdown, and skip-trowel blending so patches do not telegraph through paint.",
        "queries": ["texture matching drywall"],
        "hero": "painting-finishing.webp",
        "scope": False,
    },
    {
        "slug": "trim-painting",
        "parent": "painting-finishing",
        "title": "Trim Painting in Pinellas County FL | Knight Group",
        "h1": "Trim painting",
        "lead": "Baseboards, casing, and door trim painted with durable enamel after repairs.",
        "queries": ["trim painting handyman"],
        "hero": "painting-finishing.webp",
        "scope": False,
    },
]

PRICING_PAGES = [
    {
        "slug": "pricing-handyman-by-the-hour",
        "title": "Handyman by the Hour in Pinellas County FL | Knight Group",
        "h1": "Handyman by the hour",
        "lead": "Transparent hourly handyman pricing for small jobs, punch lists, and mixed repairs in Pinellas County.",
        "queries": ["handyman by the hour"],
    },
    {
        "slug": "pricing-flat-rate-handyman",
        "title": "Flat Rate Handyman Pricing | Pinellas County FL",
        "h1": "Flat rate handyman pricing",
        "lead": "Written flat-rate quotes for defined scopes so you know the number before work starts.",
        "queries": ["flat rate handyman"],
    },
    {
        "slug": "pricing-plumbing-repair-prices",
        "title": "Handyman Plumbing Prices | Pinellas County FL",
        "h1": "Handyman plumbing repair prices",
        "lead": "Fixture-level plumbing pricing for faucets, toilets, disposals, and minor leak corrections within handyman scope.",
        "queries": ["handyman plumbing prices"],
    },
    {
        "slug": "pricing-no-2-hour-minimum",
        "title": "No 2-Hour Minimum Handyman | Pinellas County FL",
        "h1": "No 2-hour minimum handyman",
        "lead": "Pay only for actual time worked from $75/hr — no franchise-style two-hour minimums on small jobs and punch lists.",
        "queries": ["handyman no 2 hour minimum", "handyman no minimum pinellas"],
    },
]

TRUST_PAGES = [
    {
        "slug": "plumber-background-handyman",
        "title": "Journeyman Plumber Handyman | Pinellas FL",
        "h1": "Why journeyman plumbing experience matters",
        "lead": "Owner Vince Knight brings 15 years of journeyman plumbing experience to handyman-scope fixture work — clearer diagnosis and honest scope, not a license claim.",
        "hero": "plumbing-services.webp",
        "breadcrumb": [("/", "Home"), ("/about", "About"), ("", "Plumbing experience")],
        "queries": ["journeyman plumber handyman florida", "experienced handyman plumber pinellas"],
    },
    {
        "slug": "rental-turnover-handyman",
        "title": "Rental Turnover Handyman | Pinellas County FL",
        "h1": "Rental turnover and punch-list handyman",
        "lead": "Move-in and move-out repairs for landlords and property managers across Pinellas County — one registered team, written estimates, tenant-ready finish.",
        "hero": "general-repairs.webp",
        "breadcrumb": [("/", "Home"), ("/services", "Services"), ("", "Rental turnover")],
        "queries": ["rental turnover punch list pinellas", "property manager handyman pinellas"],
    },
    {
        "slug": "handyman-scope-florida",
        "title": "Handyman Scope in Florida | Pinellas County",
        "h1": "Handyman scope in Florida",
        "lead": "Knight Group is registered and insured — not a licensed plumber, electrician, or GC. We handle handyman-scope work honestly and refer licensed trades when required.",
        "hero": "handyman.webp",
        "breadcrumb": [("/", "Home"), ("/about", "About"), ("", "Handyman scope")],
        "queries": ["what can a handyman do in florida", "registered handyman pinellas county"],
    },
    {
        "slug": "hurricane-repair-handyman-pinellas",
        "title": "Hurricane Prep & Storm Repair | Pinellas FL",
        "h1": "Hurricane prep and storm repair handyman",
        "lead": "Registered and insured handyman help before and after Pinellas County storms — caulk, boarding, water-damage follow-up, and punch lists when you need a local team, not a franchise minimum.",
        "hero": "emergency-services.webp",
        "breadcrumb": [("/", "Home"), ("/Services/emergency-services", "Emergency"), ("", "Hurricane prep")],
        "queries": ["hurricane repair handyman pinellas county", "storm damage handyman pinellas"],
    },
]

CITY_COMBOS = [
    ("clearwater", "sink-repair", "Clearwater", "sink and faucet repair", "plumbing-services", "sink-faucet-repair"),
    ("clearwater", "drywall-repair", "Clearwater", "drywall repair", "general-repairs", "drywall-repair"),
    ("safety-harbor", "home-repair", "Safety Harbor", "home repair", "handyman", "home-repair-near-me"),
]

PARENT_LABELS = {
    "handyman": "Handyman Services",
    "general-repairs": "General Repairs",
    "plumbing-services": "Plumbing Services",
    "electrical-work": "Electrical Work",
    "carpentry-framing": "Carpentry & Framing",
    "painting-finishing": "Painting & Finishing",
    "home-renovations": "Home Renovations",
    "doors-windows": "Doors & Windows",
    "custom-projects": "Custom Projects",
    "emergency-services": "Emergency Services",
}
